module Main

// the null0-cart-grain docker image provides null0.gr; you only need to
// ship your own copy if you build outside docker
from "./null0.gr" include Null0

// called on load
@unsafe
provide let load = () => {
  Null0.initColors()
  Null0.clear(Null0.blue)
  Null0.draw_circle(100n, 100n, 50n, Null0.red)
}

// called on every frame
provide let update = () => void

// other callbacks you can implement:
// provide let unload = () => void
// @unsafe
// provide let buttonUp = (button: WasmI32, player: WasmI32) => void
// @unsafe
// provide let buttonDown = (button: WasmI32, player: WasmI32) => void
// @unsafe
// provide let keyUp = (key: WasmI32) => void
// @unsafe
// provide let keyDown = (key: WasmI32) => void
// @unsafe
// provide let mouseDown = (button: WasmI32) => void
// @unsafe
// provide let mouseUp = (button: WasmI32) => void
// @unsafe
// provide let mouseMoved = (x: WasmF32, y: WasmF32) => void
