// null0 - C glue between haxe HL/C carts and the null0 host imports
//
// Generated by tools/gen_cart_haxe.js - do not edit.
//
// Every null0 API function gets a null0hx_<name>() shim that the generated
// haxe bindings call via @:hlNative("null0hx", ...). The shim adapts the
// HL/C calling convention to the null0 wasm ABI:
//   - haxe Strings are UTF-16, converted with hl_to_utf8 (GC-owned)
//   - Array<T> of structs is an ArrayObj of pointers, copied to a
//     contiguous buffer for the host
//   - Array<Int> is an ArrayBytes_Int, passed as (bytes, length)
//   - struct args/returns are plain pointers on both sides

#include <hl.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define NULL0_IMPORT(n) __attribute__((import_module("null0"), import_name(n)))
#define NULL0_EXPORT(n) __attribute__((export_name(n)))

// haxe runtime layouts (must match what HLC generates for Null0.hx)
typedef struct {
  hl_type *type;
  vbyte *bytes; // UTF-16
  int length;
} *HxString;

typedef struct {
  hl_type *type;
  int length;
  varray *array;
} *HxArrayObj;

typedef struct {
  hl_type *type;
  int length;
  vbyte *bytes;
  int size;
} *HxArrayBytesInt;

typedef struct {
  unsigned int randSeed;
  int waveType;
  float attackTime;
  float sustainTime;
  float sustainPunch;
  float decayTime;
  float startFrequency;
  float minFrequency;
  float slide;
  float deltaSlide;
  float vibratoDepth;
  float vibratoSpeed;
  float changeAmount;
  float changeSpeed;
  float squareDuty;
  float dutySweep;
  float repeatSpeed;
  float phaserOffset;
  float phaserSweep;
  float lpfCutoff;
  float lpfCutoffSweep;
  float lpfResonance;
  float hpfCutoff;
  float hpfCutoffSweep;
} HxSfxParams;

typedef struct {
  int width;
  int height;
} HxDimensions;

typedef struct {
  int x;
  int y;
} HxVector;

typedef struct {
  int x;
  int y;
  int width;
  int height;
} HxRectangle;

typedef struct {
  unsigned char r;
  unsigned char g;
  unsigned char b;
  unsigned char a;
} HxColor;

// colors

NULL0_IMPORT("color_tint")
static HxColor * host_color_tint(HxColor * color, HxColor * tint);
HxColor * null0hx_color_tint(HxColor * color, HxColor * tint) {
  HxColor * ret = host_color_tint(color, tint);
  return ret;
}

NULL0_IMPORT("color_fade")
static HxColor * host_color_fade(HxColor * color, float alpha);
HxColor * null0hx_color_fade(HxColor * color, float alpha) {
  HxColor * ret = host_color_fade(color, alpha);
  return ret;
}

NULL0_IMPORT("color_brightness")
static HxColor * host_color_brightness(HxColor * color, float factor);
HxColor * null0hx_color_brightness(HxColor * color, float factor) {
  HxColor * ret = host_color_brightness(color, factor);
  return ret;
}

NULL0_IMPORT("color_invert")
static HxColor * host_color_invert(HxColor * color);
HxColor * null0hx_color_invert(HxColor * color) {
  HxColor * ret = host_color_invert(color);
  return ret;
}

NULL0_IMPORT("color_alpha_blend")
static HxColor * host_color_alpha_blend(HxColor * dst, HxColor * src);
HxColor * null0hx_color_alpha_blend(HxColor * dst, HxColor * src) {
  HxColor * ret = host_color_alpha_blend(dst, src);
  return ret;
}

NULL0_IMPORT("color_contrast")
static HxColor * host_color_contrast(HxColor * color, float contrast);
HxColor * null0hx_color_contrast(HxColor * color, float contrast) {
  HxColor * ret = host_color_contrast(color, contrast);
  return ret;
}

NULL0_IMPORT("color_bilinear_interpolate")
static HxColor * host_color_bilinear_interpolate(HxColor * color00, HxColor * color01, HxColor * color10, HxColor * color11, float coordinateX, float coordinateY);
HxColor * null0hx_color_bilinear_interpolate(HxColor * color00, HxColor * color01, HxColor * color10, HxColor * color11, float coordinateX, float coordinateY) {
  HxColor * ret = host_color_bilinear_interpolate(color00, color01, color10, color11, coordinateX, coordinateY);
  return ret;
}

// graphics

NULL0_IMPORT("new_image")
static unsigned int host_new_image(int width, int height, HxColor * color);
unsigned int null0hx_new_image(int width, int height, HxColor * color) {
  unsigned int ret = host_new_image(width, height, color);
  return ret;
}

NULL0_IMPORT("image_copy")
static unsigned int host_image_copy(unsigned int image);
unsigned int null0hx_image_copy(unsigned int image) {
  unsigned int ret = host_image_copy(image);
  return ret;
}

NULL0_IMPORT("image_subimage")
static unsigned int host_image_subimage(unsigned int image, int x, int y, int width, int height);
unsigned int null0hx_image_subimage(unsigned int image, int x, int y, int width, int height) {
  unsigned int ret = host_image_subimage(image, x, y, width, height);
  return ret;
}

NULL0_IMPORT("clear")
static void host_clear(HxColor * color);
void null0hx_clear(HxColor * color) {
  host_clear(color);
}

NULL0_IMPORT("draw_point")
static void host_draw_point(int x, int y, HxColor * color);
void null0hx_draw_point(int x, int y, HxColor * color) {
  host_draw_point(x, y, color);
}

NULL0_IMPORT("draw_line")
static void host_draw_line(int startPosX, int startPosY, int endPosX, int endPosY, HxColor * color);
void null0hx_draw_line(int startPosX, int startPosY, int endPosX, int endPosY, HxColor * color) {
  host_draw_line(startPosX, startPosY, endPosX, endPosY, color);
}

NULL0_IMPORT("draw_rectangle")
static void host_draw_rectangle(int posX, int posY, int width, int height, HxColor * color);
void null0hx_draw_rectangle(int posX, int posY, int width, int height, HxColor * color) {
  host_draw_rectangle(posX, posY, width, height, color);
}

NULL0_IMPORT("draw_triangle")
static void host_draw_triangle(int x1, int y1, int x2, int y2, int x3, int y3, HxColor * color);
void null0hx_draw_triangle(int x1, int y1, int x2, int y2, int x3, int y3, HxColor * color) {
  host_draw_triangle(x1, y1, x2, y2, x3, y3, color);
}

NULL0_IMPORT("draw_ellipse")
static void host_draw_ellipse(int centerX, int centerY, int radiusX, int radiusY, HxColor * color);
void null0hx_draw_ellipse(int centerX, int centerY, int radiusX, int radiusY, HxColor * color) {
  host_draw_ellipse(centerX, centerY, radiusX, radiusY, color);
}

NULL0_IMPORT("draw_circle")
static void host_draw_circle(int centerX, int centerY, int radius, HxColor * color);
void null0hx_draw_circle(int centerX, int centerY, int radius, HxColor * color) {
  host_draw_circle(centerX, centerY, radius, color);
}

NULL0_IMPORT("draw_polygon")
static void host_draw_polygon(HxVector * points, int numPoints, HxColor * color);
void null0hx_draw_polygon(HxArrayObj points, HxColor * color) {
  varray *points_arr = points->array;
  HxVector *points_buf = (HxVector *)hl_aptr(points_arr, HxVector);
  if (points_arr->at->kind != HSTRUCT) {
    points_buf = (HxVector *)malloc(sizeof(HxVector) * points->length);
    for (int points_i = 0; points_i < points->length; points_i++) {
      void *points_e = hl_aptr(points_arr, void *)[points_i];
      if (points_arr->at->kind == HDYN) points_e = ((vdynamic *)points_e)->v.ptr;
      points_buf[points_i] = *(HxVector *)points_e;
    }
  }
  host_draw_polygon(points_buf, points->length, color);
  if (points_arr->at->kind != HSTRUCT) free(points_buf);
}

NULL0_IMPORT("draw_arc")
static void host_draw_arc(int centerX, int centerY, float radius, float startAngle, float endAngle, int segments, HxColor * color);
void null0hx_draw_arc(int centerX, int centerY, float radius, float startAngle, float endAngle, int segments, HxColor * color) {
  host_draw_arc(centerX, centerY, radius, startAngle, endAngle, segments, color);
}

NULL0_IMPORT("draw_rectangle_rounded")
static void host_draw_rectangle_rounded(int x, int y, int width, int height, int cornerRadius, HxColor * color);
void null0hx_draw_rectangle_rounded(int x, int y, int width, int height, int cornerRadius, HxColor * color) {
  host_draw_rectangle_rounded(x, y, width, height, cornerRadius, color);
}

NULL0_IMPORT("draw_image")
static void host_draw_image(unsigned int src, int posX, int posY);
void null0hx_draw_image(unsigned int src, int posX, int posY) {
  host_draw_image(src, posX, posY);
}

NULL0_IMPORT("draw_image_tint")
static void host_draw_image_tint(unsigned int src, int posX, int posY, HxColor * tint);
void null0hx_draw_image_tint(unsigned int src, int posX, int posY, HxColor * tint) {
  host_draw_image_tint(src, posX, posY, tint);
}

NULL0_IMPORT("draw_image_rotated")
static void host_draw_image_rotated(unsigned int src, int posX, int posY, float degrees, float offsetX, float offsetY, int filter);
void null0hx_draw_image_rotated(unsigned int src, int posX, int posY, float degrees, float offsetX, float offsetY, int filter) {
  host_draw_image_rotated(src, posX, posY, degrees, offsetX, offsetY, filter);
}

NULL0_IMPORT("draw_image_flipped")
static void host_draw_image_flipped(unsigned int src, int posX, int posY, bool flipHorizontal, bool flipVertical, bool flipDiagonal);
void null0hx_draw_image_flipped(unsigned int src, int posX, int posY, bool flipHorizontal, bool flipVertical, bool flipDiagonal) {
  host_draw_image_flipped(src, posX, posY, flipHorizontal, flipVertical, flipDiagonal);
}

NULL0_IMPORT("draw_image_scaled")
static void host_draw_image_scaled(unsigned int src, int posX, int posY, float scaleX, float scaleY, float offsetX, float offsetY, int filter);
void null0hx_draw_image_scaled(unsigned int src, int posX, int posY, float scaleX, float scaleY, float offsetX, float offsetY, int filter) {
  host_draw_image_scaled(src, posX, posY, scaleX, scaleY, offsetX, offsetY, filter);
}

NULL0_IMPORT("draw_text")
static void host_draw_text(unsigned int font, char * text, int posX, int posY, HxColor * color);
void null0hx_draw_text(unsigned int font, HxString text, int posX, int posY, HxColor * color) {
  host_draw_text(font, hl_to_utf8((uchar *)text->bytes), posX, posY, color);
}

NULL0_IMPORT("save_image")
static void host_save_image(unsigned int image, char * filename);
void null0hx_save_image(unsigned int image, HxString filename) {
  host_save_image(image, hl_to_utf8((uchar *)filename->bytes));
}

NULL0_IMPORT("load_image")
static unsigned int host_load_image(char * filename);
unsigned int null0hx_load_image(HxString filename) {
  unsigned int ret = host_load_image(hl_to_utf8((uchar *)filename->bytes));
  return ret;
}

NULL0_IMPORT("image_resize")
static unsigned int host_image_resize(unsigned int image, int newWidth, int newHeight, int filter);
unsigned int null0hx_image_resize(unsigned int image, int newWidth, int newHeight, int filter) {
  unsigned int ret = host_image_resize(image, newWidth, newHeight, filter);
  return ret;
}

NULL0_IMPORT("image_scale")
static unsigned int host_image_scale(unsigned int image, float scaleX, float scaleY, int filter);
unsigned int null0hx_image_scale(unsigned int image, float scaleX, float scaleY, int filter) {
  unsigned int ret = host_image_scale(image, scaleX, scaleY, filter);
  return ret;
}

NULL0_IMPORT("image_color_replace")
static void host_image_color_replace(unsigned int image, HxColor * color, HxColor * replace);
void null0hx_image_color_replace(unsigned int image, HxColor * color, HxColor * replace) {
  host_image_color_replace(image, color, replace);
}

NULL0_IMPORT("image_color_tint")
static void host_image_color_tint(unsigned int image, HxColor * color);
void null0hx_image_color_tint(unsigned int image, HxColor * color) {
  host_image_color_tint(image, color);
}

NULL0_IMPORT("image_color_fade")
static void host_image_color_fade(unsigned int image, float alpha);
void null0hx_image_color_fade(unsigned int image, float alpha) {
  host_image_color_fade(image, alpha);
}

NULL0_IMPORT("font_copy")
static unsigned int host_font_copy(unsigned int font);
unsigned int null0hx_font_copy(unsigned int font) {
  unsigned int ret = host_font_copy(font);
  return ret;
}

NULL0_IMPORT("font_scale")
static unsigned int host_font_scale(unsigned int font, float scaleX, float scaleY, int filter);
unsigned int null0hx_font_scale(unsigned int font, float scaleX, float scaleY, int filter) {
  unsigned int ret = host_font_scale(font, scaleX, scaleY, filter);
  return ret;
}

NULL0_IMPORT("load_font_bmf")
static unsigned int host_load_font_bmf(char * filename, char * characters);
unsigned int null0hx_load_font_bmf(HxString filename, HxString characters) {
  unsigned int ret = host_load_font_bmf(hl_to_utf8((uchar *)filename->bytes), hl_to_utf8((uchar *)characters->bytes));
  return ret;
}

NULL0_IMPORT("load_font_bmf_from_image")
static unsigned int host_load_font_bmf_from_image(unsigned int image, char * characters);
unsigned int null0hx_load_font_bmf_from_image(unsigned int image, HxString characters) {
  unsigned int ret = host_load_font_bmf_from_image(image, hl_to_utf8((uchar *)characters->bytes));
  return ret;
}

NULL0_IMPORT("measure_text")
static HxDimensions * host_measure_text(unsigned int font, char * text, int textLength);
HxDimensions * null0hx_measure_text(unsigned int font, HxString text, int textLength) {
  HxDimensions * ret = host_measure_text(font, hl_to_utf8((uchar *)text->bytes), textLength);
  return ret;
}

NULL0_IMPORT("measure_image")
static HxDimensions * host_measure_image(unsigned int image);
HxDimensions * null0hx_measure_image(unsigned int image) {
  HxDimensions * ret = host_measure_image(image);
  return ret;
}

NULL0_IMPORT("load_font_tty")
static unsigned int host_load_font_tty(char * filename, int glyphWidth, int glyphHeight, char * characters);
unsigned int null0hx_load_font_tty(HxString filename, int glyphWidth, int glyphHeight, HxString characters) {
  unsigned int ret = host_load_font_tty(hl_to_utf8((uchar *)filename->bytes), glyphWidth, glyphHeight, hl_to_utf8((uchar *)characters->bytes));
  return ret;
}

NULL0_IMPORT("load_font_tty_from_image")
static unsigned int host_load_font_tty_from_image(unsigned int image, int glyphWidth, int glyphHeight, char * characters);
unsigned int null0hx_load_font_tty_from_image(unsigned int image, int glyphWidth, int glyphHeight, HxString characters) {
  unsigned int ret = host_load_font_tty_from_image(image, glyphWidth, glyphHeight, hl_to_utf8((uchar *)characters->bytes));
  return ret;
}

NULL0_IMPORT("load_font_ttf")
static unsigned int host_load_font_ttf(char * filename, int fontSize);
unsigned int null0hx_load_font_ttf(HxString filename, int fontSize) {
  unsigned int ret = host_load_font_ttf(hl_to_utf8((uchar *)filename->bytes), fontSize);
  return ret;
}

NULL0_IMPORT("image_color_invert")
static void host_image_color_invert(unsigned int image);
void null0hx_image_color_invert(unsigned int image) {
  host_image_color_invert(image);
}

NULL0_IMPORT("image_alpha_border")
static HxRectangle * host_image_alpha_border(unsigned int image, float threshold);
HxRectangle * null0hx_image_alpha_border(unsigned int image, float threshold) {
  HxRectangle * ret = host_image_alpha_border(image, threshold);
  return ret;
}

NULL0_IMPORT("image_crop")
static void host_image_crop(unsigned int image, int x, int y, int width, int height);
void null0hx_image_crop(unsigned int image, int x, int y, int width, int height) {
  host_image_crop(image, x, y, width, height);
}

NULL0_IMPORT("image_alpha_crop")
static void host_image_alpha_crop(unsigned int image, float threshold);
void null0hx_image_alpha_crop(unsigned int image, float threshold) {
  host_image_alpha_crop(image, threshold);
}

NULL0_IMPORT("image_color_brightness")
static void host_image_color_brightness(unsigned int image, float factor);
void null0hx_image_color_brightness(unsigned int image, float factor) {
  host_image_color_brightness(image, factor);
}

NULL0_IMPORT("image_flip")
static void host_image_flip(unsigned int image, bool horizontal, bool vertical);
void null0hx_image_flip(unsigned int image, bool horizontal, bool vertical) {
  host_image_flip(image, horizontal, vertical);
}

NULL0_IMPORT("image_color_contrast")
static void host_image_color_contrast(unsigned int image, float contrast);
void null0hx_image_color_contrast(unsigned int image, float contrast) {
  host_image_color_contrast(image, contrast);
}

NULL0_IMPORT("image_alpha_mask")
static void host_image_alpha_mask(unsigned int image, unsigned int alphaMask, int posX, int posY);
void null0hx_image_alpha_mask(unsigned int image, unsigned int alphaMask, int posX, int posY) {
  host_image_alpha_mask(image, alphaMask, posX, posY);
}

NULL0_IMPORT("image_rotate")
static unsigned int host_image_rotate(unsigned int image, float degrees, int filter);
unsigned int null0hx_image_rotate(unsigned int image, float degrees, int filter) {
  unsigned int ret = host_image_rotate(image, degrees, filter);
  return ret;
}

NULL0_IMPORT("image_gradient")
static unsigned int host_image_gradient(int width, int height, HxColor * topLeft, HxColor * topRight, HxColor * bottomLeft, HxColor * bottomRight);
unsigned int null0hx_image_gradient(int width, int height, HxColor * topLeft, HxColor * topRight, HxColor * bottomLeft, HxColor * bottomRight) {
  unsigned int ret = host_image_gradient(width, height, topLeft, topRight, bottomLeft, bottomRight);
  return ret;
}

NULL0_IMPORT("unload_image")
static void host_unload_image(unsigned int image);
void null0hx_unload_image(unsigned int image) {
  host_unload_image(image);
}

NULL0_IMPORT("unload_font")
static void host_unload_font(unsigned int font);
void null0hx_unload_font(unsigned int font) {
  host_unload_font(font);
}

NULL0_IMPORT("clear_image")
static void host_clear_image(unsigned int destination, HxColor * color);
void null0hx_clear_image(unsigned int destination, HxColor * color) {
  host_clear_image(destination, color);
}

NULL0_IMPORT("draw_point_on_image")
static void host_draw_point_on_image(unsigned int destination, int x, int y, HxColor * color);
void null0hx_draw_point_on_image(unsigned int destination, int x, int y, HxColor * color) {
  host_draw_point_on_image(destination, x, y, color);
}

NULL0_IMPORT("draw_line_on_image")
static void host_draw_line_on_image(unsigned int destination, int startPosX, int startPosY, int endPosX, int endPosY, HxColor * color);
void null0hx_draw_line_on_image(unsigned int destination, int startPosX, int startPosY, int endPosX, int endPosY, HxColor * color) {
  host_draw_line_on_image(destination, startPosX, startPosY, endPosX, endPosY, color);
}

NULL0_IMPORT("draw_rectangle_on_image")
static void host_draw_rectangle_on_image(unsigned int destination, int posX, int posY, int width, int height, HxColor * color);
void null0hx_draw_rectangle_on_image(unsigned int destination, int posX, int posY, int width, int height, HxColor * color) {
  host_draw_rectangle_on_image(destination, posX, posY, width, height, color);
}

NULL0_IMPORT("draw_triangle_on_image")
static void host_draw_triangle_on_image(unsigned int destination, int x1, int y1, int x2, int y2, int x3, int y3, HxColor * color);
void null0hx_draw_triangle_on_image(unsigned int destination, int x1, int y1, int x2, int y2, int x3, int y3, HxColor * color) {
  host_draw_triangle_on_image(destination, x1, y1, x2, y2, x3, y3, color);
}

NULL0_IMPORT("draw_ellipse_on_image")
static void host_draw_ellipse_on_image(unsigned int destination, int centerX, int centerY, int radiusX, int radiusY, HxColor * color);
void null0hx_draw_ellipse_on_image(unsigned int destination, int centerX, int centerY, int radiusX, int radiusY, HxColor * color) {
  host_draw_ellipse_on_image(destination, centerX, centerY, radiusX, radiusY, color);
}

NULL0_IMPORT("draw_circle_on_image")
static void host_draw_circle_on_image(unsigned int destination, int centerX, int centerY, int radius, HxColor * color);
void null0hx_draw_circle_on_image(unsigned int destination, int centerX, int centerY, int radius, HxColor * color) {
  host_draw_circle_on_image(destination, centerX, centerY, radius, color);
}

NULL0_IMPORT("draw_polygon_on_image")
static void host_draw_polygon_on_image(unsigned int destination, HxVector * points, int numPoints, HxColor * color);
void null0hx_draw_polygon_on_image(unsigned int destination, HxArrayObj points, HxColor * color) {
  varray *points_arr = points->array;
  HxVector *points_buf = (HxVector *)hl_aptr(points_arr, HxVector);
  if (points_arr->at->kind != HSTRUCT) {
    points_buf = (HxVector *)malloc(sizeof(HxVector) * points->length);
    for (int points_i = 0; points_i < points->length; points_i++) {
      void *points_e = hl_aptr(points_arr, void *)[points_i];
      if (points_arr->at->kind == HDYN) points_e = ((vdynamic *)points_e)->v.ptr;
      points_buf[points_i] = *(HxVector *)points_e;
    }
  }
  host_draw_polygon_on_image(destination, points_buf, points->length, color);
  if (points_arr->at->kind != HSTRUCT) free(points_buf);
}

NULL0_IMPORT("draw_rectangle_rounded_on_image")
static void host_draw_rectangle_rounded_on_image(unsigned int destination, int x, int y, int width, int height, int cornerRadius, HxColor * color);
void null0hx_draw_rectangle_rounded_on_image(unsigned int destination, int x, int y, int width, int height, int cornerRadius, HxColor * color) {
  host_draw_rectangle_rounded_on_image(destination, x, y, width, height, cornerRadius, color);
}

NULL0_IMPORT("draw_image_on_image")
static void host_draw_image_on_image(unsigned int destination, unsigned int src, int posX, int posY);
void null0hx_draw_image_on_image(unsigned int destination, unsigned int src, int posX, int posY) {
  host_draw_image_on_image(destination, src, posX, posY);
}

NULL0_IMPORT("draw_image_tint_on_image")
static void host_draw_image_tint_on_image(unsigned int destination, unsigned int src, int posX, int posY, HxColor * tint);
void null0hx_draw_image_tint_on_image(unsigned int destination, unsigned int src, int posX, int posY, HxColor * tint) {
  host_draw_image_tint_on_image(destination, src, posX, posY, tint);
}

NULL0_IMPORT("draw_image_rotated_on_image")
static void host_draw_image_rotated_on_image(unsigned int destination, unsigned int src, int posX, int posY, float degrees, float offsetX, float offsetY, int filter);
void null0hx_draw_image_rotated_on_image(unsigned int destination, unsigned int src, int posX, int posY, float degrees, float offsetX, float offsetY, int filter) {
  host_draw_image_rotated_on_image(destination, src, posX, posY, degrees, offsetX, offsetY, filter);
}

NULL0_IMPORT("draw_image_flipped_on_image")
static void host_draw_image_flipped_on_image(unsigned int destination, unsigned int src, int posX, int posY, bool flipHorizontal, bool flipVertical, bool flipDiagonal);
void null0hx_draw_image_flipped_on_image(unsigned int destination, unsigned int src, int posX, int posY, bool flipHorizontal, bool flipVertical, bool flipDiagonal) {
  host_draw_image_flipped_on_image(destination, src, posX, posY, flipHorizontal, flipVertical, flipDiagonal);
}

NULL0_IMPORT("draw_image_scaled_on_image")
static void host_draw_image_scaled_on_image(unsigned int destination, unsigned int src, int posX, int posY, float scaleX, float scaleY, float offsetX, float offsetY, int filter);
void null0hx_draw_image_scaled_on_image(unsigned int destination, unsigned int src, int posX, int posY, float scaleX, float scaleY, float offsetX, float offsetY, int filter) {
  host_draw_image_scaled_on_image(destination, src, posX, posY, scaleX, scaleY, offsetX, offsetY, filter);
}

NULL0_IMPORT("draw_text_on_image")
static void host_draw_text_on_image(unsigned int destination, unsigned int font, char * text, int posX, int posY, HxColor * color);
void null0hx_draw_text_on_image(unsigned int destination, unsigned int font, HxString text, int posX, int posY, HxColor * color) {
  host_draw_text_on_image(destination, font, hl_to_utf8((uchar *)text->bytes), posX, posY, color);
}

NULL0_IMPORT("draw_rectangle_outline")
static void host_draw_rectangle_outline(int posX, int posY, int width, int height, int thickness, HxColor * color);
void null0hx_draw_rectangle_outline(int posX, int posY, int width, int height, int thickness, HxColor * color) {
  host_draw_rectangle_outline(posX, posY, width, height, thickness, color);
}

NULL0_IMPORT("draw_triangle_outline")
static void host_draw_triangle_outline(int x1, int y1, int x2, int y2, int x3, int y3, int thickness, HxColor * color);
void null0hx_draw_triangle_outline(int x1, int y1, int x2, int y2, int x3, int y3, int thickness, HxColor * color) {
  host_draw_triangle_outline(x1, y1, x2, y2, x3, y3, thickness, color);
}

NULL0_IMPORT("draw_ellipse_outline")
static void host_draw_ellipse_outline(int centerX, int centerY, int radiusX, int radiusY, int thickness, HxColor * color);
void null0hx_draw_ellipse_outline(int centerX, int centerY, int radiusX, int radiusY, int thickness, HxColor * color) {
  host_draw_ellipse_outline(centerX, centerY, radiusX, radiusY, thickness, color);
}

NULL0_IMPORT("draw_circle_outline")
static void host_draw_circle_outline(int centerX, int centerY, int radius, int thickness, HxColor * color);
void null0hx_draw_circle_outline(int centerX, int centerY, int radius, int thickness, HxColor * color) {
  host_draw_circle_outline(centerX, centerY, radius, thickness, color);
}

NULL0_IMPORT("draw_polygon_outline")
static void host_draw_polygon_outline(HxVector * points, int numPoints, int thickness, HxColor * color);
void null0hx_draw_polygon_outline(HxArrayObj points, int thickness, HxColor * color) {
  varray *points_arr = points->array;
  HxVector *points_buf = (HxVector *)hl_aptr(points_arr, HxVector);
  if (points_arr->at->kind != HSTRUCT) {
    points_buf = (HxVector *)malloc(sizeof(HxVector) * points->length);
    for (int points_i = 0; points_i < points->length; points_i++) {
      void *points_e = hl_aptr(points_arr, void *)[points_i];
      if (points_arr->at->kind == HDYN) points_e = ((vdynamic *)points_e)->v.ptr;
      points_buf[points_i] = *(HxVector *)points_e;
    }
  }
  host_draw_polygon_outline(points_buf, points->length, thickness, color);
  if (points_arr->at->kind != HSTRUCT) free(points_buf);
}

NULL0_IMPORT("draw_arc_outline")
static void host_draw_arc_outline(int centerX, int centerY, float radius, float startAngle, float endAngle, int segments, int thickness, HxColor * color);
void null0hx_draw_arc_outline(int centerX, int centerY, float radius, float startAngle, float endAngle, int segments, int thickness, HxColor * color) {
  host_draw_arc_outline(centerX, centerY, radius, startAngle, endAngle, segments, thickness, color);
}

NULL0_IMPORT("draw_rectangle_rounded_outline")
static void host_draw_rectangle_rounded_outline(int x, int y, int width, int height, int cornerRadius, int thickness, HxColor * color);
void null0hx_draw_rectangle_rounded_outline(int x, int y, int width, int height, int cornerRadius, int thickness, HxColor * color) {
  host_draw_rectangle_rounded_outline(x, y, width, height, cornerRadius, thickness, color);
}

NULL0_IMPORT("draw_rectangle_outline_on_image")
static void host_draw_rectangle_outline_on_image(unsigned int destination, int posX, int posY, int width, int height, int thickness, HxColor * color);
void null0hx_draw_rectangle_outline_on_image(unsigned int destination, int posX, int posY, int width, int height, int thickness, HxColor * color) {
  host_draw_rectangle_outline_on_image(destination, posX, posY, width, height, thickness, color);
}

NULL0_IMPORT("draw_triangle_outline_on_image")
static void host_draw_triangle_outline_on_image(unsigned int destination, int x1, int y1, int x2, int y2, int x3, int y3, int thickness, HxColor * color);
void null0hx_draw_triangle_outline_on_image(unsigned int destination, int x1, int y1, int x2, int y2, int x3, int y3, int thickness, HxColor * color) {
  host_draw_triangle_outline_on_image(destination, x1, y1, x2, y2, x3, y3, thickness, color);
}

NULL0_IMPORT("draw_ellipse_outline_on_image")
static void host_draw_ellipse_outline_on_image(unsigned int destination, int centerX, int centerY, int radiusX, int radiusY, int thickness, HxColor * color);
void null0hx_draw_ellipse_outline_on_image(unsigned int destination, int centerX, int centerY, int radiusX, int radiusY, int thickness, HxColor * color) {
  host_draw_ellipse_outline_on_image(destination, centerX, centerY, radiusX, radiusY, thickness, color);
}

NULL0_IMPORT("draw_circle_outline_on_image")
static void host_draw_circle_outline_on_image(unsigned int destination, int centerX, int centerY, int radius, int thickness, HxColor * color);
void null0hx_draw_circle_outline_on_image(unsigned int destination, int centerX, int centerY, int radius, int thickness, HxColor * color) {
  host_draw_circle_outline_on_image(destination, centerX, centerY, radius, thickness, color);
}

NULL0_IMPORT("draw_polygon_outline_on_image")
static void host_draw_polygon_outline_on_image(unsigned int destination, HxVector * points, int numPoints, int thickness, HxColor * color);
void null0hx_draw_polygon_outline_on_image(unsigned int destination, HxArrayObj points, int thickness, HxColor * color) {
  varray *points_arr = points->array;
  HxVector *points_buf = (HxVector *)hl_aptr(points_arr, HxVector);
  if (points_arr->at->kind != HSTRUCT) {
    points_buf = (HxVector *)malloc(sizeof(HxVector) * points->length);
    for (int points_i = 0; points_i < points->length; points_i++) {
      void *points_e = hl_aptr(points_arr, void *)[points_i];
      if (points_arr->at->kind == HDYN) points_e = ((vdynamic *)points_e)->v.ptr;
      points_buf[points_i] = *(HxVector *)points_e;
    }
  }
  host_draw_polygon_outline_on_image(destination, points_buf, points->length, thickness, color);
  if (points_arr->at->kind != HSTRUCT) free(points_buf);
}

NULL0_IMPORT("draw_rectangle_rounded_outline_on_image")
static void host_draw_rectangle_rounded_outline_on_image(unsigned int destination, int x, int y, int width, int height, int cornerRadius, int thickness, HxColor * color);
void null0hx_draw_rectangle_rounded_outline_on_image(unsigned int destination, int x, int y, int width, int height, int cornerRadius, int thickness, HxColor * color) {
  host_draw_rectangle_rounded_outline_on_image(destination, x, y, width, height, cornerRadius, thickness, color);
}

// gui

NULL0_IMPORT("gui_begin_window")
static bool host_gui_begin_window(char * title, HxRectangle * rect);
bool null0hx_gui_begin_window(HxString title, HxRectangle * rect) {
  bool ret = host_gui_begin_window(hl_to_utf8((uchar *)title->bytes), rect);
  return ret;
}

NULL0_IMPORT("gui_end_window")
static void host_gui_end_window(void);
void null0hx_gui_end_window(void) {
  host_gui_end_window();
}

NULL0_IMPORT("gui_button")
static bool host_gui_button(char * label);
bool null0hx_gui_button(HxString label) {
  bool ret = host_gui_button(hl_to_utf8((uchar *)label->bytes));
  return ret;
}

NULL0_IMPORT("gui_label")
static void host_gui_label(char * text);
void null0hx_gui_label(HxString text) {
  host_gui_label(hl_to_utf8((uchar *)text->bytes));
}

NULL0_IMPORT("gui_text")
static void host_gui_text(char * text);
void null0hx_gui_text(HxString text) {
  host_gui_text(hl_to_utf8((uchar *)text->bytes));
}

NULL0_IMPORT("gui_checkbox")
static bool host_gui_checkbox(char * label, bool state);
bool null0hx_gui_checkbox(HxString label, bool state) {
  bool ret = host_gui_checkbox(hl_to_utf8((uchar *)label->bytes), state);
  return ret;
}

NULL0_IMPORT("gui_slider")
static float host_gui_slider(float value, float low, float high);
float null0hx_gui_slider(float value, float low, float high) {
  float ret = host_gui_slider(value, low, high);
  return ret;
}

NULL0_IMPORT("gui_layout_row")
static void host_gui_layout_row(int * widths, int numWidths, int height);
void null0hx_gui_layout_row(HxArrayBytesInt widths, int height) {
  host_gui_layout_row((int *)widths->bytes, widths->length, height);
}

NULL0_IMPORT("gui_end")
static void host_gui_end(void);
void null0hx_gui_end(void) {
  host_gui_end();
}

NULL0_IMPORT("gui_draw")
static void host_gui_draw(unsigned int dst);
void null0hx_gui_draw(unsigned int dst) {
  host_gui_draw(dst);
}

// input

NULL0_IMPORT("key_pressed")
static bool host_key_pressed(int key);
bool null0hx_key_pressed(int key) {
  bool ret = host_key_pressed(key);
  return ret;
}

NULL0_IMPORT("key_down")
static bool host_key_down(int key);
bool null0hx_key_down(int key) {
  bool ret = host_key_down(key);
  return ret;
}

NULL0_IMPORT("key_released")
static bool host_key_released(int key);
bool null0hx_key_released(int key) {
  bool ret = host_key_released(key);
  return ret;
}

NULL0_IMPORT("key_up")
static bool host_key_up(int key);
bool null0hx_key_up(int key) {
  bool ret = host_key_up(key);
  return ret;
}

NULL0_IMPORT("gamepad_button_pressed")
static bool host_gamepad_button_pressed(int gamepad, int button);
bool null0hx_gamepad_button_pressed(int gamepad, int button) {
  bool ret = host_gamepad_button_pressed(gamepad, button);
  return ret;
}

NULL0_IMPORT("gamepad_button_down")
static bool host_gamepad_button_down(int gamepad, int button);
bool null0hx_gamepad_button_down(int gamepad, int button) {
  bool ret = host_gamepad_button_down(gamepad, button);
  return ret;
}

NULL0_IMPORT("gamepad_button_released")
static bool host_gamepad_button_released(int gamepad, int button);
bool null0hx_gamepad_button_released(int gamepad, int button) {
  bool ret = host_gamepad_button_released(gamepad, button);
  return ret;
}

NULL0_IMPORT("mouse_position")
static HxVector * host_mouse_position(void);
HxVector * null0hx_mouse_position(void) {
  HxVector * ret = host_mouse_position();
  return ret;
}

NULL0_IMPORT("mouse_button_pressed")
static bool host_mouse_button_pressed(int button);
bool null0hx_mouse_button_pressed(int button) {
  bool ret = host_mouse_button_pressed(button);
  return ret;
}

NULL0_IMPORT("mouse_button_down")
static bool host_mouse_button_down(int button);
bool null0hx_mouse_button_down(int button) {
  bool ret = host_mouse_button_down(button);
  return ret;
}

NULL0_IMPORT("mouse_button_released")
static bool host_mouse_button_released(int button);
bool null0hx_mouse_button_released(int button) {
  bool ret = host_mouse_button_released(button);
  return ret;
}

NULL0_IMPORT("mouse_button_up")
static bool host_mouse_button_up(int button);
bool null0hx_mouse_button_up(int button) {
  bool ret = host_mouse_button_up(button);
  return ret;
}

// sound

NULL0_IMPORT("load_sound")
static unsigned int host_load_sound(char * filename);
unsigned int null0hx_load_sound(HxString filename) {
  unsigned int ret = host_load_sound(hl_to_utf8((uchar *)filename->bytes));
  return ret;
}

NULL0_IMPORT("play_sound")
static void host_play_sound(unsigned int sound, bool loop);
void null0hx_play_sound(unsigned int sound, bool loop) {
  host_play_sound(sound, loop);
}

NULL0_IMPORT("stop_sound")
static void host_stop_sound(unsigned int sound);
void null0hx_stop_sound(unsigned int sound) {
  host_stop_sound(sound);
}

NULL0_IMPORT("unload_sound")
static void host_unload_sound(unsigned int sound);
void null0hx_unload_sound(unsigned int sound) {
  host_unload_sound(sound);
}

NULL0_IMPORT("tts_sound")
static unsigned int host_tts_sound(char * text, bool phonetic, int pitch, int speed, int throat, int mouth, bool sing);
unsigned int null0hx_tts_sound(HxString text, bool phonetic, int pitch, int speed, int throat, int mouth, bool sing) {
  unsigned int ret = host_tts_sound(hl_to_utf8((uchar *)text->bytes), phonetic, pitch, speed, throat, mouth, sing);
  return ret;
}

NULL0_IMPORT("sfx_sound")
static unsigned int host_sfx_sound(HxSfxParams * params);
unsigned int null0hx_sfx_sound(HxSfxParams * params) {
  unsigned int ret = host_sfx_sound(params);
  return ret;
}

NULL0_IMPORT("sfx_generate")
static HxSfxParams * host_sfx_generate(int type);
HxSfxParams * null0hx_sfx_generate(int type) {
  HxSfxParams * ret = host_sfx_generate(type);
  return ret;
}

// tile

NULL0_IMPORT("load_tilemap")
static unsigned int host_load_tilemap(char * filename);
unsigned int null0hx_load_tilemap(HxString filename) {
  unsigned int ret = host_load_tilemap(hl_to_utf8((uchar *)filename->bytes));
  return ret;
}

NULL0_IMPORT("unload_tilemap")
static void host_unload_tilemap(unsigned int tilemap);
void null0hx_unload_tilemap(unsigned int tilemap) {
  host_unload_tilemap(tilemap);
}

NULL0_IMPORT("tile_update")
static void host_tile_update(unsigned int tilemap, float deltaTime);
void null0hx_tile_update(unsigned int tilemap, float deltaTime) {
  host_tile_update(tilemap, deltaTime);
}

NULL0_IMPORT("tile_draw")
static void host_tile_draw(unsigned int tilemap, int posX, int posY);
void null0hx_tile_draw(unsigned int tilemap, int posX, int posY) {
  host_tile_draw(tilemap, posX, posY);
}

NULL0_IMPORT("tile_draw_tint")
static void host_tile_draw_tint(unsigned int tilemap, int posX, int posY, HxColor * tint);
void null0hx_tile_draw_tint(unsigned int tilemap, int posX, int posY, HxColor * tint) {
  host_tile_draw_tint(tilemap, posX, posY, tint);
}

NULL0_IMPORT("tile_draw_on_image")
static void host_tile_draw_on_image(unsigned int dst, unsigned int tilemap, int posX, int posY);
void null0hx_tile_draw_on_image(unsigned int dst, unsigned int tilemap, int posX, int posY) {
  host_tile_draw_on_image(dst, tilemap, posX, posY);
}

NULL0_IMPORT("tile_draw_tile")
static void host_tile_draw_tile(unsigned int tilemap, int gid, int posX, int posY);
void null0hx_tile_draw_tile(unsigned int tilemap, int gid, int posX, int posY) {
  host_tile_draw_tile(tilemap, gid, posX, posY);
}

NULL0_IMPORT("tile_layer_count")
static int host_tile_layer_count(unsigned int tilemap);
int null0hx_tile_layer_count(unsigned int tilemap) {
  int ret = host_tile_layer_count(tilemap);
  return ret;
}

NULL0_IMPORT("tile_get_tile")
static int host_tile_get_tile(unsigned int tilemap, int layer, int column, int row);
int null0hx_tile_get_tile(unsigned int tilemap, int layer, int column, int row) {
  int ret = host_tile_get_tile(tilemap, layer, column, row);
  return ret;
}

NULL0_IMPORT("tile_set_tile")
static void host_tile_set_tile(unsigned int tilemap, int layer, int column, int row, int gid);
void null0hx_tile_set_tile(unsigned int tilemap, int layer, int column, int row, int gid) {
  host_tile_set_tile(tilemap, layer, column, row, gid);
}

NULL0_IMPORT("tile_image")
static unsigned int host_tile_image(unsigned int tilemap, int gid);
unsigned int null0hx_tile_image(unsigned int tilemap, int gid) {
  unsigned int ret = host_tile_image(tilemap, gid);
  return ret;
}

NULL0_IMPORT("tilemap_image")
static unsigned int host_tilemap_image(unsigned int tilemap);
unsigned int null0hx_tilemap_image(unsigned int tilemap) {
  unsigned int ret = host_tilemap_image(tilemap);
  return ret;
}

// types

// utilities

NULL0_IMPORT("current_time")
static int64_t host_current_time(void);
int64_t null0hx_current_time(void) {
  int64_t ret = host_current_time();
  return ret;
}

NULL0_IMPORT("delta_time")
static float host_delta_time(void);
float null0hx_delta_time(void) {
  float ret = host_delta_time();
  return ret;
}

NULL0_IMPORT("random_int")
static int host_random_int(int min, int max);
int null0hx_random_int(int min, int max) {
  int ret = host_random_int(min, max);
  return ret;
}

NULL0_IMPORT("random_seed_get")
static int64_t host_random_seed_get(void);
int64_t null0hx_random_seed_get(void) {
  int64_t ret = host_random_seed_get();
  return ret;
}

NULL0_IMPORT("random_seed_set")
static void host_random_seed_set(int64_t seed);
void null0hx_random_seed_set(int64_t seed) {
  host_random_seed_set(seed);
}

// callbacks

static vclosure *cb_load;
static vclosure *cb_update;
static vclosure *cb_unload;
static vclosure *cb_buttonUp;
static vclosure *cb_buttonDown;
static vclosure *cb_keyUp;
static vclosure *cb_keyDown;
static vclosure *cb_mouseDown;
static vclosure *cb_mouseUp;
static vclosure *cb_mouseMoved;

void null0hx_set_callback(HxString name, vdynamic *cb) {
  char *n = hl_to_utf8((uchar *)name->bytes);
  vclosure **slot = NULL;
  if (strcmp(n, "load") == 0) slot = &cb_load;
  if (strcmp(n, "update") == 0) slot = &cb_update;
  if (strcmp(n, "unload") == 0) slot = &cb_unload;
  if (strcmp(n, "buttonUp") == 0) slot = &cb_buttonUp;
  if (strcmp(n, "buttonDown") == 0) slot = &cb_buttonDown;
  if (strcmp(n, "keyUp") == 0) slot = &cb_keyUp;
  if (strcmp(n, "keyDown") == 0) slot = &cb_keyDown;
  if (strcmp(n, "mouseDown") == 0) slot = &cb_mouseDown;
  if (strcmp(n, "mouseUp") == 0) slot = &cb_mouseUp;
  if (strcmp(n, "mouseMoved") == 0) slot = &cb_mouseMoved;
  if (slot == NULL) return;
  *slot = (vclosure *)cb;
  hl_add_root((void **)slot);
}

NULL0_EXPORT("load")
void load(void) {
  vclosure *cl = cb_load;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *))cl->fun)(cl->value);
  else
    ((void (*)(void))cl->fun)();
}

NULL0_EXPORT("update")
void update(void) {
  vclosure *cl = cb_update;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *))cl->fun)(cl->value);
  else
    ((void (*)(void))cl->fun)();
}

NULL0_EXPORT("unload")
void unload(void) {
  vclosure *cl = cb_unload;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *))cl->fun)(cl->value);
  else
    ((void (*)(void))cl->fun)();
}

NULL0_EXPORT("buttonUp")
void buttonUp(int button, unsigned int player) {
  vclosure *cl = cb_buttonUp;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *, int, unsigned int))cl->fun)(cl->value, button, player);
  else
    ((void (*)(int, unsigned int))cl->fun)(button, player);
}

NULL0_EXPORT("buttonDown")
void buttonDown(int button, unsigned int player) {
  vclosure *cl = cb_buttonDown;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *, int, unsigned int))cl->fun)(cl->value, button, player);
  else
    ((void (*)(int, unsigned int))cl->fun)(button, player);
}

NULL0_EXPORT("keyUp")
void keyUp(int key) {
  vclosure *cl = cb_keyUp;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *, int))cl->fun)(cl->value, key);
  else
    ((void (*)(int))cl->fun)(key);
}

NULL0_EXPORT("keyDown")
void keyDown(int key) {
  vclosure *cl = cb_keyDown;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *, int))cl->fun)(cl->value, key);
  else
    ((void (*)(int))cl->fun)(key);
}

NULL0_EXPORT("mouseDown")
void mouseDown(int button) {
  vclosure *cl = cb_mouseDown;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *, int))cl->fun)(cl->value, button);
  else
    ((void (*)(int))cl->fun)(button);
}

NULL0_EXPORT("mouseUp")
void mouseUp(int button) {
  vclosure *cl = cb_mouseUp;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *, int))cl->fun)(cl->value, button);
  else
    ((void (*)(int))cl->fun)(button);
}

NULL0_EXPORT("mouseMoved")
void mouseMoved(float x, float y) {
  vclosure *cl = cb_mouseMoved;
  if (cl == NULL) return;
  if (cl->hasValue)
    ((void (*)(void *, float, float))cl->fun)(cl->value, x, y);
  else
    ((void (*)(float, float))cl->fun)(x, y);
}
