// null0 - COBOL shim (generated by gen_cart_cobol.js)
// cobc -static generates direct C calls to int-returning functions;
// these wrappers forward them to the real null0 host-imports.
//
// Limitations:
// - f32 returns (delta_time) come back as raw int32 bits
// - u64 returns (current_time, random_seed_get) are truncated to int32
#include <stdint.h>


// COLORS
__attribute__((import_module("null0"), import_name("color_tint")))
extern uint32_t n0_color_tint(uint32_t color, uint32_t tint);
int color_tint(int color, int tint) { return (int)n0_color_tint(color, tint); }

__attribute__((import_module("null0"), import_name("color_fade")))
extern uint32_t n0_color_fade(uint32_t color, float alpha);
int color_fade(int color, float alpha) { return (int)n0_color_fade(color, alpha); }

__attribute__((import_module("null0"), import_name("color_brightness")))
extern uint32_t n0_color_brightness(uint32_t color, float factor);
int color_brightness(int color, float factor) { return (int)n0_color_brightness(color, factor); }

__attribute__((import_module("null0"), import_name("color_invert")))
extern uint32_t n0_color_invert(uint32_t color);
int color_invert(int color) { return (int)n0_color_invert(color); }

__attribute__((import_module("null0"), import_name("color_alpha_blend")))
extern uint32_t n0_color_alpha_blend(uint32_t dst, uint32_t src);
int color_alpha_blend(int dst, int src) { return (int)n0_color_alpha_blend(dst, src); }

__attribute__((import_module("null0"), import_name("color_contrast")))
extern uint32_t n0_color_contrast(uint32_t color, float contrast);
int color_contrast(int color, float contrast) { return (int)n0_color_contrast(color, contrast); }

__attribute__((import_module("null0"), import_name("color_bilinear_interpolate")))
extern uint32_t n0_color_bilinear_interpolate(uint32_t color00, uint32_t color01, uint32_t color10, uint32_t color11, float coordinateX, float coordinateY);
int color_bilinear_interpolate(int color00, int color01, int color10, int color11, float coordinateX, float coordinateY) { return (int)n0_color_bilinear_interpolate(color00, color01, color10, color11, coordinateX, coordinateY); }


// GRAPHICS
__attribute__((import_module("null0"), import_name("new_image")))
extern uint32_t n0_new_image(int32_t width, int32_t height, uint32_t color);
int new_image(int width, int height, int color) { return (int)n0_new_image(width, height, color); }

__attribute__((import_module("null0"), import_name("image_copy")))
extern uint32_t n0_image_copy(uint32_t image);
int image_copy(int image) { return (int)n0_image_copy(image); }

__attribute__((import_module("null0"), import_name("image_subimage")))
extern uint32_t n0_image_subimage(uint32_t image, int32_t x, int32_t y, int32_t width, int32_t height);
int image_subimage(int image, int x, int y, int width, int height) { return (int)n0_image_subimage(image, x, y, width, height); }

__attribute__((import_module("null0"), import_name("clear")))
extern void n0_clear(uint32_t color);
int clear(int color) { n0_clear(color); return 0; }

__attribute__((import_module("null0"), import_name("draw_point")))
extern void n0_draw_point(int32_t x, int32_t y, uint32_t color);
int draw_point(int x, int y, int color) { n0_draw_point(x, y, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_line")))
extern void n0_draw_line(int32_t startPosX, int32_t startPosY, int32_t endPosX, int32_t endPosY, uint32_t color);
int draw_line(int startPosX, int startPosY, int endPosX, int endPosY, int color) { n0_draw_line(startPosX, startPosY, endPosX, endPosY, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_rectangle")))
extern void n0_draw_rectangle(int32_t posX, int32_t posY, int32_t width, int32_t height, uint32_t color);
int draw_rectangle(int posX, int posY, int width, int height, int color) { n0_draw_rectangle(posX, posY, width, height, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_triangle")))
extern void n0_draw_triangle(int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, uint32_t color);
int draw_triangle(int x1, int y1, int x2, int y2, int x3, int y3, int color) { n0_draw_triangle(x1, y1, x2, y2, x3, y3, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_ellipse")))
extern void n0_draw_ellipse(int32_t centerX, int32_t centerY, int32_t radiusX, int32_t radiusY, uint32_t color);
int draw_ellipse(int centerX, int centerY, int radiusX, int radiusY, int color) { n0_draw_ellipse(centerX, centerY, radiusX, radiusY, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_circle")))
extern void n0_draw_circle(int32_t centerX, int32_t centerY, int32_t radius, uint32_t color);
int draw_circle(int centerX, int centerY, int radius, int color) { n0_draw_circle(centerX, centerY, radius, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_polygon")))
extern void n0_draw_polygon(uint32_t points, int32_t numPoints, uint32_t color);
int draw_polygon(void* points, int numPoints, int color) { n0_draw_polygon((uint32_t)(uintptr_t)points, numPoints, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_arc")))
extern void n0_draw_arc(int32_t centerX, int32_t centerY, float radius, float startAngle, float endAngle, int32_t segments, uint32_t color);
int draw_arc(int centerX, int centerY, float radius, float startAngle, float endAngle, int segments, int color) { n0_draw_arc(centerX, centerY, radius, startAngle, endAngle, segments, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_rectangle_rounded")))
extern void n0_draw_rectangle_rounded(int32_t x, int32_t y, int32_t width, int32_t height, int32_t cornerRadius, uint32_t color);
int draw_rectangle_rounded(int x, int y, int width, int height, int cornerRadius, int color) { n0_draw_rectangle_rounded(x, y, width, height, cornerRadius, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_image")))
extern void n0_draw_image(uint32_t src, int32_t posX, int32_t posY);
int draw_image(int src, int posX, int posY) { n0_draw_image(src, posX, posY); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_tint")))
extern void n0_draw_image_tint(uint32_t src, int32_t posX, int32_t posY, uint32_t tint);
int draw_image_tint(int src, int posX, int posY, int tint) { n0_draw_image_tint(src, posX, posY, tint); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_rotated")))
extern void n0_draw_image_rotated(uint32_t src, int32_t posX, int32_t posY, float degrees, float offsetX, float offsetY, int32_t filter);
int draw_image_rotated(int src, int posX, int posY, float degrees, float offsetX, float offsetY, int filter) { n0_draw_image_rotated(src, posX, posY, degrees, offsetX, offsetY, filter); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_flipped")))
extern void n0_draw_image_flipped(uint32_t src, int32_t posX, int32_t posY, int32_t flipHorizontal, int32_t flipVertical, int32_t flipDiagonal);
int draw_image_flipped(int src, int posX, int posY, int flipHorizontal, int flipVertical, int flipDiagonal) { n0_draw_image_flipped(src, posX, posY, flipHorizontal, flipVertical, flipDiagonal); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_scaled")))
extern void n0_draw_image_scaled(uint32_t src, int32_t posX, int32_t posY, float scaleX, float scaleY, float offsetX, float offsetY, int32_t filter);
int draw_image_scaled(int src, int posX, int posY, float scaleX, float scaleY, float offsetX, float offsetY, int filter) { n0_draw_image_scaled(src, posX, posY, scaleX, scaleY, offsetX, offsetY, filter); return 0; }

__attribute__((import_module("null0"), import_name("draw_text")))
extern void n0_draw_text(uint32_t font, uint32_t text, int32_t posX, int32_t posY, uint32_t color);
int draw_text(int font, char* text, int posX, int posY, int color) { n0_draw_text(font, (uint32_t)(uintptr_t)text, posX, posY, color); return 0; }

__attribute__((import_module("null0"), import_name("save_image")))
extern void n0_save_image(uint32_t image, uint32_t filename);
int save_image(int image, char* filename) { n0_save_image(image, (uint32_t)(uintptr_t)filename); return 0; }

__attribute__((import_module("null0"), import_name("load_image")))
extern uint32_t n0_load_image(uint32_t filename);
int load_image(char* filename) { return (int)n0_load_image((uint32_t)(uintptr_t)filename); }

__attribute__((import_module("null0"), import_name("image_resize")))
extern uint32_t n0_image_resize(uint32_t image, int32_t newWidth, int32_t newHeight, int32_t filter);
int image_resize(int image, int newWidth, int newHeight, int filter) { return (int)n0_image_resize(image, newWidth, newHeight, filter); }

__attribute__((import_module("null0"), import_name("image_scale")))
extern uint32_t n0_image_scale(uint32_t image, float scaleX, float scaleY, int32_t filter);
int image_scale(int image, float scaleX, float scaleY, int filter) { return (int)n0_image_scale(image, scaleX, scaleY, filter); }

__attribute__((import_module("null0"), import_name("image_color_replace")))
extern void n0_image_color_replace(uint32_t image, uint32_t color, uint32_t replace);
int image_color_replace(int image, int color, int replace) { n0_image_color_replace(image, color, replace); return 0; }

__attribute__((import_module("null0"), import_name("image_color_tint")))
extern void n0_image_color_tint(uint32_t image, uint32_t color);
int image_color_tint(int image, int color) { n0_image_color_tint(image, color); return 0; }

__attribute__((import_module("null0"), import_name("image_color_fade")))
extern void n0_image_color_fade(uint32_t image, float alpha);
int image_color_fade(int image, float alpha) { n0_image_color_fade(image, alpha); return 0; }

__attribute__((import_module("null0"), import_name("font_copy")))
extern uint32_t n0_font_copy(uint32_t font);
int font_copy(int font) { return (int)n0_font_copy(font); }

__attribute__((import_module("null0"), import_name("font_scale")))
extern uint32_t n0_font_scale(uint32_t font, float scaleX, float scaleY, int32_t filter);
int font_scale(int font, float scaleX, float scaleY, int filter) { return (int)n0_font_scale(font, scaleX, scaleY, filter); }

__attribute__((import_module("null0"), import_name("load_font_bmf")))
extern uint32_t n0_load_font_bmf(uint32_t filename, uint32_t characters);
int load_font_bmf(char* filename, char* characters) { return (int)n0_load_font_bmf((uint32_t)(uintptr_t)filename, (uint32_t)(uintptr_t)characters); }

__attribute__((import_module("null0"), import_name("load_font_bmf_from_image")))
extern uint32_t n0_load_font_bmf_from_image(uint32_t image, uint32_t characters);
int load_font_bmf_from_image(int image, char* characters) { return (int)n0_load_font_bmf_from_image(image, (uint32_t)(uintptr_t)characters); }

__attribute__((import_module("null0"), import_name("measure_text")))
extern uint32_t n0_measure_text(uint32_t font, uint32_t text, int32_t textLength);
int measure_text(int font, char* text, int textLength) { return (int)n0_measure_text(font, (uint32_t)(uintptr_t)text, textLength); }

__attribute__((import_module("null0"), import_name("measure_image")))
extern uint32_t n0_measure_image(uint32_t image);
int measure_image(int image) { return (int)n0_measure_image(image); }

__attribute__((import_module("null0"), import_name("load_font_tty")))
extern uint32_t n0_load_font_tty(uint32_t filename, int32_t glyphWidth, int32_t glyphHeight, uint32_t characters);
int load_font_tty(char* filename, int glyphWidth, int glyphHeight, char* characters) { return (int)n0_load_font_tty((uint32_t)(uintptr_t)filename, glyphWidth, glyphHeight, (uint32_t)(uintptr_t)characters); }

__attribute__((import_module("null0"), import_name("load_font_tty_from_image")))
extern uint32_t n0_load_font_tty_from_image(uint32_t image, int32_t glyphWidth, int32_t glyphHeight, uint32_t characters);
int load_font_tty_from_image(int image, int glyphWidth, int glyphHeight, char* characters) { return (int)n0_load_font_tty_from_image(image, glyphWidth, glyphHeight, (uint32_t)(uintptr_t)characters); }

__attribute__((import_module("null0"), import_name("load_font_ttf")))
extern uint32_t n0_load_font_ttf(uint32_t filename, int32_t fontSize);
int load_font_ttf(char* filename, int fontSize) { return (int)n0_load_font_ttf((uint32_t)(uintptr_t)filename, fontSize); }

__attribute__((import_module("null0"), import_name("image_color_invert")))
extern void n0_image_color_invert(uint32_t image);
int image_color_invert(int image) { n0_image_color_invert(image); return 0; }

__attribute__((import_module("null0"), import_name("image_alpha_border")))
extern uint32_t n0_image_alpha_border(uint32_t image, float threshold);
int image_alpha_border(int image, float threshold) { return (int)n0_image_alpha_border(image, threshold); }

__attribute__((import_module("null0"), import_name("image_crop")))
extern void n0_image_crop(uint32_t image, int32_t x, int32_t y, int32_t width, int32_t height);
int image_crop(int image, int x, int y, int width, int height) { n0_image_crop(image, x, y, width, height); return 0; }

__attribute__((import_module("null0"), import_name("image_alpha_crop")))
extern void n0_image_alpha_crop(uint32_t image, float threshold);
int image_alpha_crop(int image, float threshold) { n0_image_alpha_crop(image, threshold); return 0; }

__attribute__((import_module("null0"), import_name("image_color_brightness")))
extern void n0_image_color_brightness(uint32_t image, float factor);
int image_color_brightness(int image, float factor) { n0_image_color_brightness(image, factor); return 0; }

__attribute__((import_module("null0"), import_name("image_flip")))
extern void n0_image_flip(uint32_t image, int32_t horizontal, int32_t vertical);
int image_flip(int image, int horizontal, int vertical) { n0_image_flip(image, horizontal, vertical); return 0; }

__attribute__((import_module("null0"), import_name("image_color_contrast")))
extern void n0_image_color_contrast(uint32_t image, float contrast);
int image_color_contrast(int image, float contrast) { n0_image_color_contrast(image, contrast); return 0; }

__attribute__((import_module("null0"), import_name("image_alpha_mask")))
extern void n0_image_alpha_mask(uint32_t image, uint32_t alphaMask, int32_t posX, int32_t posY);
int image_alpha_mask(int image, int alphaMask, int posX, int posY) { n0_image_alpha_mask(image, alphaMask, posX, posY); return 0; }

__attribute__((import_module("null0"), import_name("image_rotate")))
extern uint32_t n0_image_rotate(uint32_t image, float degrees, int32_t filter);
int image_rotate(int image, float degrees, int filter) { return (int)n0_image_rotate(image, degrees, filter); }

__attribute__((import_module("null0"), import_name("image_gradient")))
extern uint32_t n0_image_gradient(int32_t width, int32_t height, uint32_t topLeft, uint32_t topRight, uint32_t bottomLeft, uint32_t bottomRight);
int image_gradient(int width, int height, int topLeft, int topRight, int bottomLeft, int bottomRight) { return (int)n0_image_gradient(width, height, topLeft, topRight, bottomLeft, bottomRight); }

__attribute__((import_module("null0"), import_name("unload_image")))
extern void n0_unload_image(uint32_t image);
int unload_image(int image) { n0_unload_image(image); return 0; }

__attribute__((import_module("null0"), import_name("unload_font")))
extern void n0_unload_font(uint32_t font);
int unload_font(int font) { n0_unload_font(font); return 0; }

__attribute__((import_module("null0"), import_name("clear_image")))
extern void n0_clear_image(uint32_t destination, uint32_t color);
int clear_image(int destination, int color) { n0_clear_image(destination, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_point_on_image")))
extern void n0_draw_point_on_image(uint32_t destination, int32_t x, int32_t y, uint32_t color);
int draw_point_on_image(int destination, int x, int y, int color) { n0_draw_point_on_image(destination, x, y, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_line_on_image")))
extern void n0_draw_line_on_image(uint32_t destination, int32_t startPosX, int32_t startPosY, int32_t endPosX, int32_t endPosY, uint32_t color);
int draw_line_on_image(int destination, int startPosX, int startPosY, int endPosX, int endPosY, int color) { n0_draw_line_on_image(destination, startPosX, startPosY, endPosX, endPosY, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_rectangle_on_image")))
extern void n0_draw_rectangle_on_image(uint32_t destination, int32_t posX, int32_t posY, int32_t width, int32_t height, uint32_t color);
int draw_rectangle_on_image(int destination, int posX, int posY, int width, int height, int color) { n0_draw_rectangle_on_image(destination, posX, posY, width, height, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_triangle_on_image")))
extern void n0_draw_triangle_on_image(uint32_t destination, int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, uint32_t color);
int draw_triangle_on_image(int destination, int x1, int y1, int x2, int y2, int x3, int y3, int color) { n0_draw_triangle_on_image(destination, x1, y1, x2, y2, x3, y3, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_ellipse_on_image")))
extern void n0_draw_ellipse_on_image(uint32_t destination, int32_t centerX, int32_t centerY, int32_t radiusX, int32_t radiusY, uint32_t color);
int draw_ellipse_on_image(int destination, int centerX, int centerY, int radiusX, int radiusY, int color) { n0_draw_ellipse_on_image(destination, centerX, centerY, radiusX, radiusY, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_circle_on_image")))
extern void n0_draw_circle_on_image(uint32_t destination, int32_t centerX, int32_t centerY, int32_t radius, uint32_t color);
int draw_circle_on_image(int destination, int centerX, int centerY, int radius, int color) { n0_draw_circle_on_image(destination, centerX, centerY, radius, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_polygon_on_image")))
extern void n0_draw_polygon_on_image(uint32_t destination, uint32_t points, int32_t numPoints, uint32_t color);
int draw_polygon_on_image(int destination, void* points, int numPoints, int color) { n0_draw_polygon_on_image(destination, (uint32_t)(uintptr_t)points, numPoints, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_rectangle_rounded_on_image")))
extern void n0_draw_rectangle_rounded_on_image(uint32_t destination, int32_t x, int32_t y, int32_t width, int32_t height, int32_t cornerRadius, uint32_t color);
int draw_rectangle_rounded_on_image(int destination, int x, int y, int width, int height, int cornerRadius, int color) { n0_draw_rectangle_rounded_on_image(destination, x, y, width, height, cornerRadius, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_on_image")))
extern void n0_draw_image_on_image(uint32_t destination, uint32_t src, int32_t posX, int32_t posY);
int draw_image_on_image(int destination, int src, int posX, int posY) { n0_draw_image_on_image(destination, src, posX, posY); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_tint_on_image")))
extern void n0_draw_image_tint_on_image(uint32_t destination, uint32_t src, int32_t posX, int32_t posY, uint32_t tint);
int draw_image_tint_on_image(int destination, int src, int posX, int posY, int tint) { n0_draw_image_tint_on_image(destination, src, posX, posY, tint); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_rotated_on_image")))
extern void n0_draw_image_rotated_on_image(uint32_t destination, uint32_t src, int32_t posX, int32_t posY, float degrees, float offsetX, float offsetY, int32_t filter);
int draw_image_rotated_on_image(int destination, int src, int posX, int posY, float degrees, float offsetX, float offsetY, int filter) { n0_draw_image_rotated_on_image(destination, src, posX, posY, degrees, offsetX, offsetY, filter); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_flipped_on_image")))
extern void n0_draw_image_flipped_on_image(uint32_t destination, uint32_t src, int32_t posX, int32_t posY, int32_t flipHorizontal, int32_t flipVertical, int32_t flipDiagonal);
int draw_image_flipped_on_image(int destination, int src, int posX, int posY, int flipHorizontal, int flipVertical, int flipDiagonal) { n0_draw_image_flipped_on_image(destination, src, posX, posY, flipHorizontal, flipVertical, flipDiagonal); return 0; }

__attribute__((import_module("null0"), import_name("draw_image_scaled_on_image")))
extern void n0_draw_image_scaled_on_image(uint32_t destination, uint32_t src, int32_t posX, int32_t posY, float scaleX, float scaleY, float offsetX, float offsetY, int32_t filter);
int draw_image_scaled_on_image(int destination, int src, int posX, int posY, float scaleX, float scaleY, float offsetX, float offsetY, int filter) { n0_draw_image_scaled_on_image(destination, src, posX, posY, scaleX, scaleY, offsetX, offsetY, filter); return 0; }

__attribute__((import_module("null0"), import_name("draw_text_on_image")))
extern void n0_draw_text_on_image(uint32_t destination, uint32_t font, uint32_t text, int32_t posX, int32_t posY, uint32_t color);
int draw_text_on_image(int destination, int font, char* text, int posX, int posY, int color) { n0_draw_text_on_image(destination, font, (uint32_t)(uintptr_t)text, posX, posY, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_rectangle_outline")))
extern void n0_draw_rectangle_outline(int32_t posX, int32_t posY, int32_t width, int32_t height, int32_t thickness, uint32_t color);
int draw_rectangle_outline(int posX, int posY, int width, int height, int thickness, int color) { n0_draw_rectangle_outline(posX, posY, width, height, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_triangle_outline")))
extern void n0_draw_triangle_outline(int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, int32_t thickness, uint32_t color);
int draw_triangle_outline(int x1, int y1, int x2, int y2, int x3, int y3, int thickness, int color) { n0_draw_triangle_outline(x1, y1, x2, y2, x3, y3, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_ellipse_outline")))
extern void n0_draw_ellipse_outline(int32_t centerX, int32_t centerY, int32_t radiusX, int32_t radiusY, int32_t thickness, uint32_t color);
int draw_ellipse_outline(int centerX, int centerY, int radiusX, int radiusY, int thickness, int color) { n0_draw_ellipse_outline(centerX, centerY, radiusX, radiusY, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_circle_outline")))
extern void n0_draw_circle_outline(int32_t centerX, int32_t centerY, int32_t radius, int32_t thickness, uint32_t color);
int draw_circle_outline(int centerX, int centerY, int radius, int thickness, int color) { n0_draw_circle_outline(centerX, centerY, radius, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_polygon_outline")))
extern void n0_draw_polygon_outline(uint32_t points, int32_t numPoints, int32_t thickness, uint32_t color);
int draw_polygon_outline(void* points, int numPoints, int thickness, int color) { n0_draw_polygon_outline((uint32_t)(uintptr_t)points, numPoints, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_arc_outline")))
extern void n0_draw_arc_outline(int32_t centerX, int32_t centerY, float radius, float startAngle, float endAngle, int32_t segments, int32_t thickness, uint32_t color);
int draw_arc_outline(int centerX, int centerY, float radius, float startAngle, float endAngle, int segments, int thickness, int color) { n0_draw_arc_outline(centerX, centerY, radius, startAngle, endAngle, segments, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_rectangle_rounded_outline")))
extern void n0_draw_rectangle_rounded_outline(int32_t x, int32_t y, int32_t width, int32_t height, int32_t cornerRadius, int32_t thickness, uint32_t color);
int draw_rectangle_rounded_outline(int x, int y, int width, int height, int cornerRadius, int thickness, int color) { n0_draw_rectangle_rounded_outline(x, y, width, height, cornerRadius, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_rectangle_outline_on_image")))
extern void n0_draw_rectangle_outline_on_image(uint32_t destination, int32_t posX, int32_t posY, int32_t width, int32_t height, int32_t thickness, uint32_t color);
int draw_rectangle_outline_on_image(int destination, int posX, int posY, int width, int height, int thickness, int color) { n0_draw_rectangle_outline_on_image(destination, posX, posY, width, height, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_triangle_outline_on_image")))
extern void n0_draw_triangle_outline_on_image(uint32_t destination, int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, int32_t thickness, uint32_t color);
int draw_triangle_outline_on_image(int destination, int x1, int y1, int x2, int y2, int x3, int y3, int thickness, int color) { n0_draw_triangle_outline_on_image(destination, x1, y1, x2, y2, x3, y3, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_ellipse_outline_on_image")))
extern void n0_draw_ellipse_outline_on_image(uint32_t destination, int32_t centerX, int32_t centerY, int32_t radiusX, int32_t radiusY, int32_t thickness, uint32_t color);
int draw_ellipse_outline_on_image(int destination, int centerX, int centerY, int radiusX, int radiusY, int thickness, int color) { n0_draw_ellipse_outline_on_image(destination, centerX, centerY, radiusX, radiusY, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_circle_outline_on_image")))
extern void n0_draw_circle_outline_on_image(uint32_t destination, int32_t centerX, int32_t centerY, int32_t radius, int32_t thickness, uint32_t color);
int draw_circle_outline_on_image(int destination, int centerX, int centerY, int radius, int thickness, int color) { n0_draw_circle_outline_on_image(destination, centerX, centerY, radius, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_polygon_outline_on_image")))
extern void n0_draw_polygon_outline_on_image(uint32_t destination, uint32_t points, int32_t numPoints, int32_t thickness, uint32_t color);
int draw_polygon_outline_on_image(int destination, void* points, int numPoints, int thickness, int color) { n0_draw_polygon_outline_on_image(destination, (uint32_t)(uintptr_t)points, numPoints, thickness, color); return 0; }

__attribute__((import_module("null0"), import_name("draw_rectangle_rounded_outline_on_image")))
extern void n0_draw_rectangle_rounded_outline_on_image(uint32_t destination, int32_t x, int32_t y, int32_t width, int32_t height, int32_t cornerRadius, int32_t thickness, uint32_t color);
int draw_rectangle_rounded_outline_on_image(int destination, int x, int y, int width, int height, int cornerRadius, int thickness, int color) { n0_draw_rectangle_rounded_outline_on_image(destination, x, y, width, height, cornerRadius, thickness, color); return 0; }


// INPUT
__attribute__((import_module("null0"), import_name("key_pressed")))
extern int32_t n0_key_pressed(int32_t key);
int key_pressed(int key) { return (int)n0_key_pressed(key); }

__attribute__((import_module("null0"), import_name("key_down")))
extern int32_t n0_key_down(int32_t key);
int key_down(int key) { return (int)n0_key_down(key); }

__attribute__((import_module("null0"), import_name("key_released")))
extern int32_t n0_key_released(int32_t key);
int key_released(int key) { return (int)n0_key_released(key); }

__attribute__((import_module("null0"), import_name("key_up")))
extern int32_t n0_key_up(int32_t key);
int key_up(int key) { return (int)n0_key_up(key); }

__attribute__((import_module("null0"), import_name("gamepad_button_pressed")))
extern int32_t n0_gamepad_button_pressed(int32_t gamepad, int32_t button);
int gamepad_button_pressed(int gamepad, int button) { return (int)n0_gamepad_button_pressed(gamepad, button); }

__attribute__((import_module("null0"), import_name("gamepad_button_down")))
extern int32_t n0_gamepad_button_down(int32_t gamepad, int32_t button);
int gamepad_button_down(int gamepad, int button) { return (int)n0_gamepad_button_down(gamepad, button); }

__attribute__((import_module("null0"), import_name("gamepad_button_released")))
extern int32_t n0_gamepad_button_released(int32_t gamepad, int32_t button);
int gamepad_button_released(int gamepad, int button) { return (int)n0_gamepad_button_released(gamepad, button); }

__attribute__((import_module("null0"), import_name("mouse_position")))
extern uint32_t n0_mouse_position();
int mouse_position() { return (int)n0_mouse_position(); }

__attribute__((import_module("null0"), import_name("mouse_button_pressed")))
extern int32_t n0_mouse_button_pressed(int32_t button);
int mouse_button_pressed(int button) { return (int)n0_mouse_button_pressed(button); }

__attribute__((import_module("null0"), import_name("mouse_button_down")))
extern int32_t n0_mouse_button_down(int32_t button);
int mouse_button_down(int button) { return (int)n0_mouse_button_down(button); }

__attribute__((import_module("null0"), import_name("mouse_button_released")))
extern int32_t n0_mouse_button_released(int32_t button);
int mouse_button_released(int button) { return (int)n0_mouse_button_released(button); }

__attribute__((import_module("null0"), import_name("mouse_button_up")))
extern int32_t n0_mouse_button_up(int32_t button);
int mouse_button_up(int button) { return (int)n0_mouse_button_up(button); }


// SOUND
__attribute__((import_module("null0"), import_name("load_sound")))
extern uint32_t n0_load_sound(uint32_t filename);
int load_sound(char* filename) { return (int)n0_load_sound((uint32_t)(uintptr_t)filename); }

__attribute__((import_module("null0"), import_name("play_sound")))
extern void n0_play_sound(uint32_t sound, int32_t loop);
int play_sound(int sound, int loop) { n0_play_sound(sound, loop); return 0; }

__attribute__((import_module("null0"), import_name("stop_sound")))
extern void n0_stop_sound(uint32_t sound);
int stop_sound(int sound) { n0_stop_sound(sound); return 0; }

__attribute__((import_module("null0"), import_name("unload_sound")))
extern void n0_unload_sound(uint32_t sound);
int unload_sound(int sound) { n0_unload_sound(sound); return 0; }

__attribute__((import_module("null0"), import_name("tts_sound")))
extern uint32_t n0_tts_sound(uint32_t text, int32_t phonetic, int32_t pitch, int32_t speed, int32_t throat, int32_t mouth, int32_t sing);
int tts_sound(char* text, int phonetic, int pitch, int speed, int throat, int mouth, int sing) { return (int)n0_tts_sound((uint32_t)(uintptr_t)text, phonetic, pitch, speed, throat, mouth, sing); }

__attribute__((import_module("null0"), import_name("sfx_sound")))
extern uint32_t n0_sfx_sound(uint32_t params);
int sfx_sound(void* params) { return (int)n0_sfx_sound((uint32_t)(uintptr_t)params); }

__attribute__((import_module("null0"), import_name("sfx_generate")))
extern uint32_t n0_sfx_generate(int32_t type);
int sfx_generate(int type) { return (int)n0_sfx_generate(type); }


// TYPES

// UTILITIES
__attribute__((import_module("null0"), import_name("current_time")))
extern uint64_t n0_current_time();
int current_time() { return (int)n0_current_time(); }

__attribute__((import_module("null0"), import_name("delta_time")))
extern float n0_delta_time();
int delta_time() { union { float f; int i; } u; u.f = n0_delta_time(); return u.i; }

__attribute__((import_module("null0"), import_name("random_int")))
extern int32_t n0_random_int(int32_t min, int32_t max);
int random_int(int min, int max) { return (int)n0_random_int(min, max); }

__attribute__((import_module("null0"), import_name("random_seed_get")))
extern uint64_t n0_random_seed_get();
int random_seed_get() { return (int)n0_random_seed_get(); }

__attribute__((import_module("null0"), import_name("random_seed_set")))
extern void n0_random_seed_set(uint64_t seed);
int random_seed_set(uint64_t seed) { n0_random_seed_set(seed); return 0; }
