#!/usr/bin/env node

// Generator for Haxe null0 API bindings
//
// Haxe carts compile via the HashLink HL/C target (`haxe -hl out/main.c`),
// and the resulting C is built with wasi-sdk. This writes two files:
//
//   carts/haxe/Null0.hx                 - the haxe API (types, constants, functions, callbacks)
//   tools/docker/haxe-cart/null0_shim.c - C glue between HL/C and the null0 wasm imports
//
// ABI notes (see AGENTS.md):
//   - structs cross as pointers; @:struct classes in haxe are plain C structs
//     with no header, so a haxe `Color` is already a `Color*` on the C side.
//   - struct returns come back from the host as cart-memory pointers; the shim
//     passes them straight through (haxe must not hold them past the callback).
//   - `T[]` args are followed by a count arg; the haxe API hides the count and
//     the shim fills it from the array length.
//   - haxe Strings are UTF-16; the shim converts with hl_to_utf8 (GC-owned).

import { writeFile, mkdir } from 'node:fs/promises'
import { getApi, seedTypes } from './utils.js'

const { constants, enums, structs, scalars, callbacks, ...api } = await getApi()

const camel = (s) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase())

// public haxe types
const hxTypes = {
  void: 'Void',
  i32: 'Int',
  u32: 'Int',
  u64: 'hl.I64',
  f32: 'Single',
  bool: 'Bool',
  string: 'String',
  Image: 'Image',
  Font: 'Font',
  Sound: 'Sound',
  Tilemap: 'Tilemap',
  Color: 'Color',
  Vector: 'Vector',
  Rectangle: 'Rectangle',
  Dimensions: 'Dimensions',
  SfxParams: 'SfxParams',
  'Vector[]': 'Array<Vector>',
  'i32[]': 'Array<Int>',
  Key: 'Key',
  GamepadButton: 'GamepadButton',
  MouseButton: 'MouseButton',
  ImageFilter: 'ImageFilter',
  SfxPresetType: 'SfxPresetType'
}

// dummy return value for native declarations (the body is never used on HL)
const hxDummy = {
  Int: '0',
  'hl.I64': '0',
  Single: '0',
  Bool: 'false',
  Image: '0',
  Font: '0',
  Sound: '0',
  Tilemap: '0',
  Key: '0',
  GamepadButton: '0',
  MouseButton: '0',
  ImageFilter: '0',
  SfxPresetType: '0'
}

// struct member types
const hxMemberTypes = {
  u8: 'hl.UI8',
  i32: 'Int',
  u32: 'Int',
  f32: 'Single',
  string: 'hl.Bytes' // read it with @:privateAccess String.fromUTF8(bytes)
}

// C types used in the shim (haxe-side calling convention)
const cTypes = {
  void: 'void',
  i32: 'int',
  u32: 'unsigned int',
  u64: 'int64_t',
  f32: 'float',
  bool: 'bool',
  string: 'HxString',
  Image: 'unsigned int',
  Font: 'unsigned int',
  Sound: 'unsigned int',
  Tilemap: 'unsigned int',
  Color: 'HxColor *',
  Vector: 'HxVector *',
  Rectangle: 'HxRectangle *',
  Dimensions: 'HxDimensions *',
  SfxParams: 'HxSfxParams *',
  'Vector[]': 'HxArrayObj',
  'i32[]': 'HxArrayBytesInt',
  Key: 'int',
  GamepadButton: 'int',
  MouseButton: 'int',
  ImageFilter: 'int',
  SfxPresetType: 'int'
}

// C types on the host-import side of the shim (the actual null0 wasm ABI)
const cHostTypes = {
  ...cTypes,
  string: 'char *',
  'Vector[]': 'HxVector *',
  'i32[]': 'int *'
}

// struct member types in the shim's mirror structs
const cMemberTypes = {
  u8: 'unsigned char',
  i32: 'int',
  u32: 'unsigned int',
  f32: 'float',
  string: 'vbyte *'
}

// a new enum/struct fills its own entries in ('@:struct' classes are laid out
// like the C structs the host writes, so they cross as plain pointers)
seedTypes(hxTypes, { enums, structs }, { enumType: (name) => name, structType: (name) => name })
seedTypes(cTypes, { enums, structs }, { enumType: 'int', structType: (name) => `Hx${name} *` })
seedTypes(hxMemberTypes, { enums }, { enumType: (name) => name })
seedTypes(cMemberTypes, { enums }, { enumType: 'int' })

// a host string arrives as raw utf8 bytes, wrapped into a haxe String below
hxTypes.string = 'String'
cTypes.string = 'HxString'

// is this arg the hidden count of the array arg before it?
const isCountArg = (argList, i) => i > 0 && argList[i - 1][1].endsWith('[]')

// args for the public haxe function: array counts are hidden
const publicArgs = (funcName, argList) => argList.filter((_, i) => !isCountArg(argList, i))

// native declaration for a function (public or private)
const hxNative = (funcName, pubName, argList, returns, isPublic) => {
  const ret = returns === 'string' ? 'hl.Bytes' : hxTypes[returns] || returns
  const params = argList.map(([n, t]) => `${n}:${hxTypes[t] || t}`).join(', ')
  const dummy = returns === 'void' ? '' : `return ${hxDummy[ret] || 'null'}; `
  return [
    `  @:hlNative("null0hx", "${funcName}")`,
  `  ${isPublic ? 'public ' : ''}static function ${pubName}(${params}):${ret} { ${dummy}}`
  ]
}

// ---------------------------------------------------------------- Null0.hx

const hx = [
  `// null0 - Haxe bindings for the null0 fantasy console
//
// Generated by tools/gen_cart_haxe.js - do not edit.
//
// Usage:
//
// \`\`\`haxe
// class Main {
//   static function main() {
//     Null0.onUpdate = () -> {
//       Null0.clear(Null0.BLUE);
//       Null0.drawCircle(100, 100, 50, Null0.RED);
//     };
//   }
// }
// \`\`\`
//
// Notes:
//   - haxe try/catch is not supported (the wasm engine carts run in has no
//     exception handling); an uncaught throw aborts the cart.
//   - functions returning structs (Color/Vector/...) return host-owned
//     objects - use them within the current callback, don't stash them.

class Null0 {
`
]

// constants
hx.push('  /** The screen image (destination handle 0). */')
hx.push('  public static inline var SCREEN:Image = 0;')
hx.push('  public static inline var SCREEN_WIDTH = 640;')
hx.push('  public static inline var SCREEN_HEIGHT = 480;')
hx.push('  /** The default font (handle 0). */')
hx.push('  public static inline var FONT_DEFAULT:Font = 0;')
hx.push('')
hx.push('  // colors')
for (const [name, def] of Object.entries(constants)) {
  if (def.type === 'Color') {
    const [r, g, b, a] = def.value
    hx.push(`  public static var ${name}(get, never):Color;`)
    hx.push(`  static inline function get_${name}():Color return new Color(${r}, ${g}, ${b}, ${a});`)
  } else if (def.type === 'string') {
    hx.push(`  public static inline var ${name} = ${JSON.stringify(def.value)};`)
  }
}
hx.push('')

// callback registration
hx.push('  // callbacks - assign these in main(), eg: Null0.onUpdate = () -> { ... }')
hx.push('')
hx.push('  @:hlNative("null0hx", "set_callback") static function _setCallback(name:String, cb:Dynamic):Void {}')
hx.push('')
const cbTypes = {
  load: 'Void->Void',
  update: 'Void->Void',
  unload: 'Void->Void',
  buttonUp: '(GamepadButton, Int)->Void',
  buttonDown: '(GamepadButton, Int)->Void',
  keyUp: '(Key)->Void',
  keyDown: '(Key)->Void',
  mouseDown: '(MouseButton)->Void',
  mouseUp: '(MouseButton)->Void',
  mouseMoved: '(Single, Single)->Void'
}
const cbDescriptions = {
  load: 'Called on load, after main().',
  update: 'Called every frame.',
  unload: 'Called when the cart is unloaded.'
}
for (const [cbName, cbType] of Object.entries(cbTypes)) {
  const desc = cbDescriptions[cbName] || callbacks[cbName]?.description || `${cbName} callback.`
  const prop = 'on' + cbName.charAt(0).toUpperCase() + cbName.slice(1)
  hx.push(`  /** ${desc} */`)
  hx.push(`  public static var ${prop}(null, set):${cbType};`)
  hx.push(`  static function set_${prop}(f:${cbType}):${cbType} {`)
  hx.push(`    _setCallback(${JSON.stringify(cbName)}, f);`)
  hx.push('    return f;')
  hx.push('  }')
  hx.push('')
}

// functions
for (const [apiName, apiObj] of Object.entries(api)) {
  hx.push(`  // ${apiName.toUpperCase()}`, '')
  for (const [funcName, { args, returns, description }] of Object.entries(apiObj)) {
    const argList = Object.entries(args)
    const pubName = camel(funcName)
    const ret = hxTypes[returns] || returns
    const hasArrayArg = argList.some(([, t]) => t.endsWith('[]'))
    const hasOptionalLength = funcName === 'measure_text'
    hx.push(`  /** ${description} */`)
    if (returns === 'string') {
      // the host hands back utf8 bytes it owns until this callback returns
      hx.push(`  public static function ${pubName}(${argList.map(([n, t]) => `${n}:${hxTypes[t] || t}`).join(', ')}):String {`)
      hx.push(`    return @:privateAccess String.fromUTF8(_${pubName}(${argList.map(([n]) => n).join(', ')}));`)
      hx.push('  }')
      hx.push(...hxNative(funcName, `_${pubName}`, argList, returns, false))
      hx.push('')
    } else if (!hasArrayArg && !hasOptionalLength) {
      // direct native binding
      hx.push(...hxNative(funcName, pubName, argList, returns, true))
      hx.push('')
    } else {
      // public wrapper + private native
      const params = publicArgs(funcName, argList)
        .map(([n, t]) => (hasOptionalLength && n === 'textLength' ? '?textLength:Int' : `${n}:${hxTypes[t] || t}`))
        .join(', ')
      hx.push(`  public static function ${pubName}(${params}):${ret} {`)
      const callArgs = publicArgs(funcName, argList).map(([n]) =>
        hasOptionalLength && n === 'textLength' ? 'textLength == null ? haxe.io.Bytes.ofString(text).length : textLength' : n
      )
      const call = `_${pubName}(${callArgs.join(', ')})`
      hx.push(`    ${returns === 'void' ? call + ';' : `return ${call};`}`)
      hx.push('  }')
      // private native: array counts are dropped (the shim fills them in)
      const privArgs = argList.filter((_, i) => !isCountArg(argList, i))
      hx.push(...hxNative(funcName, `_${pubName}`, privArgs, returns, false))
      hx.push('')
    }
  }
}

hx.push('}')
hx.push('')

// structs as @:struct classes (layout matches the host ABI exactly)
for (const [structName, structDef] of Object.entries(structs)) {
  hx.push(`/** ${structDef.description} */`)
  hx.push('@:struct')
  hx.push(`class ${structName} {`)
  for (const [memberName, memberType] of Object.entries(structDef.members)) {
    hx.push(`  public var ${memberName}:${hxMemberTypes[memberType] || memberType};`)
  }
  const params = Object.entries(structDef.members)
    .map(([n, t]) => `${n}:${hxMemberTypes[t] || t} = ${structName === 'Color' && n === 'a' ? 255 : 0}`)
    .join(', ')
  hx.push(`  public function new(${params}) {`)
  for (const memberName of Object.keys(structDef.members)) {
    hx.push(`    this.${memberName} = ${memberName};`)
  }
  hx.push('  }')
  hx.push('}')
  hx.push('')
}

// enums as enum abstracts
for (const [enumName, enumDef] of Object.entries(enums)) {
  hx.push(`/** ${enumDef.description} */`)
  hx.push(`enum abstract ${enumName}(Int) from Int to Int {`)
  for (const [valueName, valueNumber] of Object.entries(enumDef.enums)) {
    hx.push(`  var ${valueName} = ${valueNumber};`)
  }
  hx.push('}')
  hx.push('')
}

// resource handles
for (const handle of ['Image', 'Font', 'Sound', 'Tilemap']) {
  hx.push(`/** ${scalars[handle]?.description || handle + ' handle.'} */`)
  hx.push(`enum abstract ${handle}(Int) from Int to Int {}`)
  hx.push('')
}

await mkdir('carts/haxe', { recursive: true })
await writeFile('carts/haxe/Null0.hx', hx.join('\n'))

// ---------------------------------------------------------------- null0_shim.c

const c = [
  `// null0 - C glue between haxe HL/C carts and the null0 host imports
//
// Generated by tools/gen_cart_haxe.js - do not edit.
//
// Every null0 API function gets a null0hx_<name>() shim that the generated
// haxe bindings call via @:hlNative("null0hx", ...). The shim adapts the
// HL/C calling convention to the null0 wasm ABI:
//   - haxe Strings are UTF-16, converted with hl_to_utf8 (GC-owned)
//   - Array<T> of structs is an ArrayObj of pointers, copied to a
//     contiguous buffer for the host
//   - Array<Int> is an ArrayBytes_Int, passed as (bytes, length)
//   - struct args/returns are plain pointers on both sides

#include <hl.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define NULL0_IMPORT(n) __attribute__((import_module("null0"), import_name(n)))
#define NULL0_EXPORT(n) __attribute__((export_name(n)))

// haxe runtime layouts (must match what HLC generates for Null0.hx)
typedef struct {
  hl_type *type;
  vbyte *bytes; // UTF-16
  int length;
} *HxString;

typedef struct {
  hl_type *type;
  int length;
  varray *array;
} *HxArrayObj;

typedef struct {
  hl_type *type;
  int length;
  vbyte *bytes;
  int size;
} *HxArrayBytesInt;
`
]

// mirror structs (layout identical to the @:struct classes in Null0.hx)
for (const [structName, structDef] of Object.entries(structs)) {
  c.push(`typedef struct {`)
  for (const [memberName, memberType] of Object.entries(structDef.members)) {
    c.push(`  ${cMemberTypes[memberType] || memberType} ${memberName};`)
  }
  c.push(`} Hx${structName};`, '')
}

// host imports + shims
for (const [apiName, apiObj] of Object.entries(api)) {
  c.push(`// ${apiName}`, '')
  for (const [funcName, { args, returns }] of Object.entries(apiObj)) {
    const argList = Object.entries(args)
    const hostParams = argList.map(([n, t]) => `${cHostTypes[t] || t} ${n}`).join(', ')
    const hostRet = returns === 'string' ? 'vbyte *' : cHostTypes[returns] || returns
    c.push(`NULL0_IMPORT("${funcName}")`)
    c.push(`static ${hostRet} host_${funcName}(${hostParams || 'void'});`)

    // shim signature: array args lose their following count arg
    const shimArgs = argList.filter((_, i) => !isCountArg(argList, i))
    const shimParams = shimArgs.map(([n, t]) => `${cTypes[t] || t} ${n}`).join(', ')
    const shimRet = returns === 'string' ? 'vbyte *' : cTypes[returns] || returns
    c.push(`${shimRet} null0hx_${funcName}(${shimParams || 'void'}) {`)

    const callArgs = []
    const pre = []
    const post = []
    for (let i = 0; i < argList.length; i++) {
      const [n, t] = argList[i]
      if (isCountArg(argList, i)) {
        callArgs.push(`${argList[i - 1][0]}->length`)
      } else if (t === 'string') {
        callArgs.push(`hl_to_utf8((uchar *)${n}->bytes)`)
      } else if (t === 'Vector[]') {
        // haxe Array<Vector> is an ArrayObj wrapping a varray, usually of
        // boxed vdynamic (element->v.ptr is the struct); HSTRUCT varrays
        // store the structs inline and can be passed straight through
        pre.push(`  varray *${n}_arr = ${n}->array;`)
        pre.push(`  HxVector *${n}_buf = (HxVector *)hl_aptr(${n}_arr, HxVector);`)
        pre.push(`  if (${n}_arr->at->kind != HSTRUCT) {`)
        pre.push(`    ${n}_buf = (HxVector *)malloc(sizeof(HxVector) * ${n}->length);`)
        pre.push(`    for (int ${n}_i = 0; ${n}_i < ${n}->length; ${n}_i++) {`)
        pre.push(`      void *${n}_e = hl_aptr(${n}_arr, void *)[${n}_i];`)
        pre.push(`      if (${n}_arr->at->kind == HDYN) ${n}_e = ((vdynamic *)${n}_e)->v.ptr;`)
        pre.push(`      ${n}_buf[${n}_i] = *(HxVector *)${n}_e;`)
        pre.push(`    }`)
        pre.push(`  }`)
        post.push(`  if (${n}_arr->at->kind != HSTRUCT) free(${n}_buf);`)
        callArgs.push(`${n}_buf`)
      } else if (t === 'i32[]') {
        callArgs.push(`(int *)${n}->bytes`)
      } else {
        callArgs.push(n)
      }
    }
    for (const line of pre) c.push(line)
    const call = `host_${funcName}(${callArgs.join(', ')})`
    if (returns === 'void') {
      c.push(`  ${call};`)
      for (const line of post) c.push(line)
    } else {
      c.push(`  ${shimRet} ret = ${call};`)
      for (const line of post) c.push(line)
      c.push('  return ret;')
    }
    c.push('}')
    c.push('')
  }
}

// callbacks: the cart assigns Null0.onUpdate etc, which registers a closure
// here; the host calls the exported load/update/... which forward to it.
c.push('// callbacks', '')
const cbList = [
  ['load', []],
  ['update', []],
  ['unload', []],
  ...Object.entries(callbacks).map(([name, def]) => [name, Object.entries(def.args || {})])
]

for (const [cbName] of cbList) {
  c.push(`static vclosure *cb_${cbName};`)
}
c.push('')
c.push('void null0hx_set_callback(HxString name, vdynamic *cb) {')
c.push('  char *n = hl_to_utf8((uchar *)name->bytes);')
c.push('  vclosure **slot = NULL;')
for (const [cbName] of cbList) {
  c.push(`  if (strcmp(n, "${cbName}") == 0) slot = &cb_${cbName};`)
}
c.push('  if (slot == NULL) return;')
c.push('  *slot = (vclosure *)cb;')
c.push('  hl_add_root((void **)slot);')
c.push('}')
c.push('')

const cbCArgTypes = { i32: 'int', u32: 'unsigned int', f32: 'float', Key: 'int', GamepadButton: 'int', MouseButton: 'int' }
for (const [cbName, cbArgs] of cbList) {
  const params = cbArgs.map(([n, t]) => `${cbCArgTypes[t] || 'int'} ${n}`).join(', ')
  const cArgList = cbArgs.map(([, t]) => cbCArgTypes[t] || 'int')
  // a haxe closure is called like generated HLC code calls it: bound
  // closures (hasValue) take their captured value as first argument
  const callWithValue = `(cl->value${cbArgs.length ? ', ' : ''}${cbArgs.map(([n]) => n).join(', ')})`
  const callPlain = `(${cbArgs.map(([n]) => n).join(', ')})`
  c.push(`NULL0_EXPORT("${cbName}")`)
  c.push(`void ${cbName}(${params || 'void'}) {`)
  c.push(`  vclosure *cl = cb_${cbName};`)
  c.push('  if (cl == NULL) return;')
  c.push('  if (cl->hasValue)')
  c.push(`    ((void (*)(void *${cArgList.length ? ', ' + cArgList.join(', ') : ''}))cl->fun)${callWithValue};`)
  c.push('  else')
  c.push(`    ((void (*)(${cArgList.join(', ') || 'void'}))cl->fun)${callPlain};`)
  c.push('}')
  c.push('')
}

await mkdir('tools/docker/haxe-cart', { recursive: true })
await writeFile('tools/docker/haxe-cart/null0_shim.c', c.join('\n'))
