// this is the shared lib for null0 API

// settings for pntr
#define PNTR_APP_RAYLIB
#define PNTR_ENABLE_DEFAULT_FONT
#define PNTR_ENABLE_TTF
#define PNTR_PIXELFORMAT_RGBA
#define PNTR_ENABLE_MATH
#define PNTR_ENABLE_JPEG
#define PNTR_NO_STB_IMAGE_IMPLEMENTATION
#define PNTR_NO_STB_IMAGE_WRITE_IMPLEMENTATION
#define PTNR_NO_STB_IMAGE_RESIZE_IMPLEMENTATION

#include "null0_api.h"