name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build cart
        run: |
          mkdir -p webroot
          rm -f webroot/mygame.null0 && docker run --rm -v ./cart:/src -v ./webroot:/out ghcr.io/notnullgames/null0-cart-onyx:latest mygame
      - name: Attach cart to release
        run: gh release upload ${{ github.event.release.tag_name }} webroot/mygame.null0
        env:
          GH_TOKEN: ${{ github.token }}
