#!/bin/bash
set -e

# Compile a Jik cart for null0

if [ -z "${1}" ]; then
    echo "Usage: $0 CART_NAME"
    echo ""
    echo "Arguments:"
    echo "  CART_NAME  Name of the output cart (without .null0 extension)"
    exit 1
fi

CART_NAME="${1}"

echo "Compiling Jik cart from /src/ to /out/"

export PATH="${PATH}:/opt/wasi-sdk/bin"

mkdir -p "/tmp/${CART_NAME}"

# Copy all files including hidden files (like .cartignore)
cp -R /src/. "/tmp/${CART_NAME}/"
cd "/tmp/${CART_NAME}/"

# Make the null0 bindings available
if [ ! -f null0.jik ]; then
    cp /usr/local/include/null0.jik .
fi
if [ ! -f null0.h ]; then
    cp /usr/local/include/null0.h .
fi

# Find the main Jik source file (main.jik or first .jik file)
MAIN_JIK="main.jik"
if [ ! -f "$MAIN_JIK" ]; then
    MAIN_JIK=$(ls *.jik 2>/dev/null | head -1)
fi

if [ -z "$MAIN_JIK" ]; then
    echo "Error: No .jik source file found"
    exit 1
fi

echo "Transpiling ${MAIN_JIK} to C..."
jik tran "$MAIN_JIK"

# jik tran outputs .c and .h files in the current directory
C_FILES=$(ls *.c 2>/dev/null)
if [ -z "$C_FILES" ]; then
    echo "Error: No C files generated by jik tran"
    exit 1
fi

# Generate export wrappers — the host calls load/update by name,
# but Jik mangles function names. Scan the generated C for the
# mangled names and create wrappers.
WRAPPER_C="_null0_exports.c"
echo "// Auto-generated export wrappers for null0 host" > "$WRAPPER_C"

# Find and wrap the load function
LOAD_FUNC=$(grep -o 'jik_src_[a-zA-Z0-9_]*_v_load' $C_FILES | head -1)
if [ -n "$LOAD_FUNC" ]; then
    echo "void ${LOAD_FUNC}(void);" >> "$WRAPPER_C"
    echo "void load(void) __attribute__((export_name(\"load\"))) { ${LOAD_FUNC}(); }" >> "$WRAPPER_C"
fi

# Find and wrap the update function
UPDATE_FUNC=$(grep -o 'jik_src_[a-zA-Z0-9_]*_v_update' $C_FILES | head -1)
if [ -n "$UPDATE_FUNC" ]; then
    echo "void ${UPDATE_FUNC}(void);" >> "$WRAPPER_C"
    echo "void update(void) __attribute__((export_name(\"update\"))) { ${UPDATE_FUNC}(); }" >> "$WRAPPER_C"
fi

C_FILES="$C_FILES $WRAPPER_C"

echo "Compiling to wasm..."
clang -I . -I /usr/local/include -I /opt/jik/support/include -nostartfiles \
    -Wl,--no-entry,--initial-memory=67108864,--max-memory=67108864,-z,stack-size=8388608 \
    -o main.wasm $C_FILES

# Package only main.wasm + assets as the cart
mkdir -p "/tmp/${CART_NAME}.pkg"
cp main.wasm "/tmp/${CART_NAME}.pkg/"
[ -d assets ] && cp -R assets "/tmp/${CART_NAME}.pkg/"

/usr/local/bin/zipcart.sh "${CART_NAME}" "/tmp/${CART_NAME}.pkg" /out
