name: Release macOS

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build Native macOS Host (universal x86_64+arm64)
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build --target host
          cd build/host
          zip ../../null0_macos.zip null0
      - name: Upload asset to release
        run: gh release upload ${{ github.event.release.tag_name }} null0_macos.zip
        env:
          GH_TOKEN: ${{ github.token }}
