name: Release macOS

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Native macOS Host (${{ matrix.arch }})
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target host
          cd build/host
          zip ../../null0_macos_${{ matrix.arch }}.zip null0
      - name: Upload asset to release
        run: gh release upload ${{ github.event.release.tag_name }} null0_macos_${{ matrix.arch }}.zip
        env:
          GH_TOKEN: ${{ github.token }}
