name: Release Windows

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Native Windows Host (x64)
        run: |
          # Use Clang-cl (Clang with MSVC-compatible interface and linking)
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DWAMR_BUILD_SIMD=0 -DWAMR_BUILD_INVOKE_NATIVE_GENERAL=1
          cmake --build build --target host

          # Create zip file
          cd build/host
          Compress-Archive -Path null0.exe -DestinationPath ../../null0_windows_x64.zip
        shell: pwsh

      - name: Upload assets to release
        run: gh release upload ${{ github.event.release.tag_name }} null0_windows_x64.zip
        env:
          GH_TOKEN: ${{ github.token }}
        shell: pwsh
