name: Release Webroot

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: release-webroot
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
      - name: Configure Web
        run: emcmake cmake -B build_web -DCMAKE_BUILD_TYPE=Release
      - name: Build Web
        run: cmake --build build_web --target host
      - name: Bundle Web
        run: |
          mkdir -p webroot/wbuild/host/
          mv build_web/host/null0.* webroot/wbuild/host/
          cd webroot
          mv mygame.html index.html
          zip -r ../webroot.zip .
      - run: gh release upload ${{github.event.release.tag_name}} webroot.zip
        env:
          GH_TOKEN: ${{ github.token }}
