name: Release Carts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: '25'
      - name: Install Nelua
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git gcc gdb
          git clone https://github.com/edubart/nelua-lang.git
          cd nelua-lang
          make
          sudo make install
      - name: Configure Carts
        run: cmake -B build_cart -DCMAKE_BUILD_TYPE=Release carts/ -DCMAKE_TOOLCHAIN_FILE=$WASI_SDK_PATH/share/cmake/wasi-sdk.cmake
      - name: Build Carts
        run: cmake --build build_cart
      - run: gh release upload ${{github.event.release.tag_name}} build_cart/*.null0
        env:
          GH_TOKEN: ${{ github.token }}
