name: Release Linux DRM (ARM)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux-drm:
    strategy:
      matrix:
        include:
          - arch: arm64
            os: ubuntu-24.04-arm64
            artifact: null0_linux_drm_arm64.zip
          - arch: armhf
            os: ubuntu-latest
            platform: linux/arm/v7
            image: arm32v7/ubuntu:24.04
            artifact: null0_linux_drm_armhf.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (for armhf)
        if: matrix.arch == 'armhf'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm

      - name: Build Native DRM Host (arm64)
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl git pkg-config cmake build-essential ninja-build zip \
            libdrm-dev libgbm-dev libegl1-mesa-dev libgles2-mesa-dev libasound2-dev libudev-dev libinput-dev libxkbcommon-dev clang
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
            -DPLATFORM=DRM -DGRAPHICS=GRAPHICS_API_OPENGL_ES2 \
            -DWAMR_BUILD_SIMD=0 -DWAMR_BUILD_INVOKE_NATIVE_GENERAL=1 \
            -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS="-Wno-unknown-warning-option -Wno-unused-command-line-argument" \
            -DCMAKE_CXX_FLAGS="-Wno-unknown-warning-option -Wno-unused-command-line-argument"
          cmake --build build --target host
          cd build/host
          zip ../../${{ matrix.artifact }} null0

      - name: Build DRM in ARM container (armhf)
        if: matrix.arch == 'armhf'
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ matrix.image }}
          options: |
            --platform=${{ matrix.platform }}
            -v ${{ github.workspace }}:/work
            -w /work
          run: |
            set -e
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y --no-install-recommends \
              ca-certificates curl git pkg-config cmake clang clang-tools ninja-build build-essential zip \
              libdrm-dev libgbm-dev libegl1-mesa-dev libgles2-mesa-dev \
              libasound2-dev libudev-dev libinput-dev libxkbcommon-dev
            update-ca-certificates || true
            cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
              -DPLATFORM=DRM -DGRAPHICS=GRAPHICS_API_OPENGL_ES2 \
              -DWAMR_BUILD_SIMD=0 -DWAMR_BUILD_INVOKE_NATIVE_GENERAL=1 \
              -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_C_FLAGS="-Wno-unknown-warning-option -Wno-unused-command-line-argument" \
              -DCMAKE_CXX_FLAGS="-Wno-unknown-warning-option -Wno-unused-command-line-argument"
            cmake --build build --target host
            cd build/host
            zip ../../${{ matrix.artifact }} null0

      - name: Upload asset to release
        run: gh release upload ${{ github.event.release.tag_name }} ${{ matrix.artifact }}
        env:
          GH_TOKEN: ${{ github.token }}
