name: Release Windows

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Build Native Windows Host (x86_64)
        shell: pwsh
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target host
          Compress-Archive -Path build/host/null0.exe -DestinationPath null0_windows.zip
      - name: Upload asset to release
        run: gh release upload ${{ github.event.release.tag_name }} null0_windows.zip
        env:
          GH_TOKEN: ${{ github.token }}
