name: JS WASM

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: '25'
      - name: Build JS Cart
        run: npm run build:cart_js
      - name: Upload asset to release
        run: gh release upload ${{ github.event.release.tag_name }} build/carts/cart-js.wasm
        env:
          GH_TOKEN: ${{ github.token }}
